using L2Monitor.Classes;
using L2Monitor.Common.Packets;
using L2Monitor.GameServer.Packets.Incomming;
using System;
using System.Collections.Generic;

namespace L2Monitor.GameServer.Packets
{
    public static class GamePacketsFromServer
    {
        private static ConnectionState[] allStates = Enum.GetValues<ConnectionState>();
        public static List<RegisteredPacket> All { get; } = new()
        {
            new RegisteredPacket("DIE",0x00, null, allStates),
            new RegisteredPacket("REVIVE",0x01, null, allStates),
            new RegisteredPacket("ATTACK_OUT_OF_RANGE",0x02, null, allStates),
            new RegisteredPacket("ATTACKIN_COOL_TIME",0x03, null, allStates),
            new RegisteredPacket("ATTACK_DEAD_TARGET",0x04, null, allStates),
            new RegisteredPacket("SPAWN_ITEM",0x05, null, allStates),
            new RegisteredPacket("SELL_LIST",0x06, null, allStates),
            new RegisteredPacket("BUY_LIST",0x07, null, allStates),
            new RegisteredPacket("DELETE_OBJECT",0x08, null, allStates),
            new RegisteredPacket("CHARACTER_SELECTION_INFO",0x09, new CharSelectInfo(), allStates),
            new RegisteredPacket("LOGIN_OUTCOME",0x0A, new LoginOutcome(), allStates),
            new RegisteredPacket("CHARACTER_SELECTED",0x0B, new CharacterSelected(), allStates),
            new RegisteredPacket("NPC_INFO",0x0C, null, allStates),
            new RegisteredPacket("NEW_CHARACTER_SUCCESS",0x0D, null, allStates),
            new RegisteredPacket("NEW_CHARACTER_FAIL",0x0E, null, allStates),
            new RegisteredPacket("CHARACTER_CREATE_SUCCESS",0x0F, null, allStates),
            new RegisteredPacket("CHARACTER_CREATE_FAIL",0x10, null, allStates),
            new RegisteredPacket("ITEM_LIST",0x11, null, allStates),
            new RegisteredPacket("SUN_RISE",0x12, null, allStates),
            new RegisteredPacket("SUN_SET",0x13, null, allStates),
            new RegisteredPacket("TRADE_START",0x14, null, allStates),
            new RegisteredPacket("TRADE_START_OK",0x15, null, allStates),
            new RegisteredPacket("DROP_ITEM",0x16, null, allStates),
            new RegisteredPacket("GET_ITEM",0x17, null, allStates),
            new RegisteredPacket("STATUS_UPDATE",0x18, null, allStates),
            new RegisteredPacket("NPC_HTML_MESSAGE",0x19, null, allStates),
            new RegisteredPacket("TRADE_OWN_ADD",0x1A, null, allStates),
            new RegisteredPacket("TRADE_OTHER_ADD",0x1B, null, allStates),
            new RegisteredPacket("TRADE_DONE",0x1C, null, allStates),
            new RegisteredPacket("CHARACTER_DELETE_SUCCESS",0x1D, null, allStates),
            new RegisteredPacket("CHARACTER_DELETE_FAIL",0x1E, null, allStates),
            new RegisteredPacket("ACTION_FAIL",0x1F, null, allStates),
            new RegisteredPacket("SEVER_CLOSE",0x20, null, allStates),
            new RegisteredPacket("INVENTORY_UPDATE",0x21, null, allStates),
            new RegisteredPacket("TELEPORT_TO_LOCATION",0x22, null, allStates),
            new RegisteredPacket("TARGET_SELECTED",0x23, null, allStates),
            new RegisteredPacket("TARGET_UNSELECTED",0x24, null, allStates),
            new RegisteredPacket("AUTO_ATTACK_START",0x25, null, allStates),
            new RegisteredPacket("AUTO_ATTACK_STOP",0x26, null, allStates),
            new RegisteredPacket("SOCIAL_ACTION",0x27, null, allStates),
            new RegisteredPacket("CHANGE_MOVE_TYPE",0x28, null, allStates),
            new RegisteredPacket("CHANGE_WAIT_TYPE",0x29, null, allStates),
            new RegisteredPacket("MANAGE_PLEDGE_POWER",0x2A, null, allStates),
            new RegisteredPacket("CREATE_PLEDGE",0x2B, null, allStates),
            new RegisteredPacket("ASK_JOIN_PLEDGE",0x2C, null, allStates),
            new RegisteredPacket("JOIN_PLEDGE",0x2D, null, allStates),
            new RegisteredPacket("KEY_PACKET",0x2E, new KeyPacket(), allStates),
            new RegisteredPacket("MOVE_TO_LOCATION",0x2F, new MoveToLocation(), allStates),
            new RegisteredPacket("NPC_SAY",0x30, null, allStates),
            new RegisteredPacket("CHAR_INFO",0x31, null, allStates),
            new RegisteredPacket("USER_INFO",0x32, null, allStates),
            new RegisteredPacket("ATTACK",0x33, null, allStates),
            new RegisteredPacket("WITHDRAWAL_PLEDGE",0x34, null, allStates),
            new RegisteredPacket("OUST_PLEDGE_MEMBER",0x35, null, allStates),
            new RegisteredPacket("SET_OUST_PLEDGE_MEMBER",0x36, null, allStates),
            new RegisteredPacket("DISMISS_PLEDGE",0x37, null, allStates),
            new RegisteredPacket("SET_DISMISS_PLEDGE",0x38, null, allStates),
            new RegisteredPacket("ASK_JOIN_PARTY",0x39, null, allStates),
            new RegisteredPacket("JOIN_PARTY",0x3A, null, allStates),
            new RegisteredPacket("WITHDRAWAL_PARTY",0x3B, null, allStates),
            new RegisteredPacket("OUST_PARTY_MEMBER",0x3C, null, allStates),
            new RegisteredPacket("SET_OUST_PARTY_MEMBER",0x3D, null, allStates),
            new RegisteredPacket("DISMISS_PARTY",0x3E, null, allStates),
            new RegisteredPacket("SET_DISMISS_PARTY",0x3F, null, allStates),
            new RegisteredPacket("MAGIC_AND_SKILL_LIST",0x40, null, allStates),
            new RegisteredPacket("WAREHOUSE_DEPOSIT_LIST",0x41, null, allStates),
            new RegisteredPacket("WAREHOUSE_WITHDRAW_LIST",0x42, null, allStates),
            new RegisteredPacket("WAREHOUSE_DONE",0x43, null, allStates),
            new RegisteredPacket("SHORT_CUT_REGISTER",0x44, null, allStates),
            new RegisteredPacket("SHORT_CUT_INIT",0x45, null, allStates),
            new RegisteredPacket("SHORT_CUT_DELETE",0x46, null, allStates),
            new RegisteredPacket("STOP_MOVE",0x47, null, allStates),
            new RegisteredPacket("MAGIC_SKILL_USE",0x48, null, allStates),
            new RegisteredPacket("MAGIC_SKILL_CANCELED",0x49, null, allStates),
            new RegisteredPacket("SAY2",0x4A, null, allStates),
            new RegisteredPacket("NPC_INFO_ABNORMAL_VISUAL_EFFECT",0x4B, null, allStates),
            new RegisteredPacket("DOOR_INFO",0x4C, null, allStates),
            new RegisteredPacket("DOOR_STATUS_UPDATE",0x4D, null, allStates),
            new RegisteredPacket("PARTY_SMALL_WINDOW_ALL",0x4E, null, allStates),
            new RegisteredPacket("PARTY_SMALL_WINDOW_ADD",0x4F, null, allStates),
            new RegisteredPacket("PARTY_SMALL_WINDOW_DELETE_ALL",0x50, null, allStates),
            new RegisteredPacket("PARTY_SMALL_WINDOW_DELETE",0x51, null, allStates),
            new RegisteredPacket("PARTY_SMALL_WINDOW_UPDATE",0x52, null, allStates),
            new RegisteredPacket("TRADE_PRESS_OWN_OK",0x53, null, allStates),
            new RegisteredPacket("MAGIC_SKILL_LAUNCHED",0x54, null, allStates),
            new RegisteredPacket("FRIEND_ADD_REQUEST_RESULT",0x55, null, allStates),
            new RegisteredPacket("FRIEND_ADD",0x56, null, allStates),
            new RegisteredPacket("FRIEND_REMOVE",0x57, null, allStates),
            new RegisteredPacket("FRIEND_LIST",0x58, null, allStates),
            new RegisteredPacket("FRIEND_STATUS",0x59, null, allStates),
            new RegisteredPacket("PLEDGE_SHOW_MEMBER_LIST_ALL",0x5A, null, allStates),
            new RegisteredPacket("PLEDGE_SHOW_MEMBER_LIST_UPDATE",0x5B, null, allStates),
            new RegisteredPacket("PLEDGE_SHOW_MEMBER_LIST_ADD",0x5C, null, allStates),
            new RegisteredPacket("PLEDGE_SHOW_MEMBER_LIST_DELETE",0x5D, null, allStates),
            new RegisteredPacket("MAGIC_LIST",0x5E, null, allStates),
            new RegisteredPacket("SKILL_LIST",0x5F, null, allStates),
            new RegisteredPacket("VEHICLE_INFO",0x60, null, allStates),
            new RegisteredPacket("FINISH_ROTATING",0x61, null, allStates),
            new RegisteredPacket("SYSTEM_MESSAGE",0x62, null, allStates),
            new RegisteredPacket("START_PLEDGE_WAR",0x63, null, allStates),
            new RegisteredPacket("REPLY_START_PLEDGE_WAR",0x64, null, allStates),
            new RegisteredPacket("STOP_PLEDGE_WAR",0x65, null, allStates),
            new RegisteredPacket("REPLY_STOP_PLEDGE_WAR",0x66, null, allStates),
            new RegisteredPacket("SURRENDER_PLEDGE_WAR",0x67, null, allStates),
            new RegisteredPacket("REPLY_SURRENDER_PLEDGE_WAR",0x68, null, allStates),
            new RegisteredPacket("SET_PLEDGE_CREST",0x69, null, allStates),
            new RegisteredPacket("PLEDGE_CREST",0x6A, null, allStates),
            new RegisteredPacket("SETUP_GAUGE",0x6B, null, allStates),
            new RegisteredPacket("VEHICLE_DEPARTURE",0x6C, null, allStates),
            new RegisteredPacket("VEHICLE_CHECK_LOCATION",0x6D, null, allStates),
            new RegisteredPacket("GET_ON_VEHICLE",0x6E, null, allStates),
            new RegisteredPacket("GET_OFF_VEHICLE",0x6F, null, allStates),
            new RegisteredPacket("TRADE_REQUEST",0x70, null, allStates),
            new RegisteredPacket("RESTART_RESPONSE",0x71, null, allStates),
            new RegisteredPacket("MOVE_TO_PAWN",0x72, null, allStates),
            new RegisteredPacket("SSQ_INFO",0x73, null, allStates),
            new RegisteredPacket("GAME_GUARD_QUERY",0x74, null, allStates),
            new RegisteredPacket("L2_FRIEND_LIST",0x75, null, allStates),
            new RegisteredPacket("L2_FRIEND",0x76, null, allStates),
            new RegisteredPacket("L2_FRIEND_STATUS",0x77, null, allStates),
            new RegisteredPacket("L2_FRIEND_SAY",0x78, null, allStates),
            new RegisteredPacket("VALIDATE_LOCATION",0x79, null, allStates),
            new RegisteredPacket("START_ROTATING",0x7A, null, allStates),
            new RegisteredPacket("SHOW_BOARD",0x7B, null, allStates),
            new RegisteredPacket("CHOOSE_INVENTORY_ITEM",0x7C, null, allStates),
            new RegisteredPacket("DUMMY",0x7D, null, allStates),
            new RegisteredPacket("MOVE_TO_LOCATION_IN_VEHICLE",0x7E, null, allStates),
            new RegisteredPacket("STOP_MOVE_IN_VEHICLE",0x7F, null, allStates),
            new RegisteredPacket("VALIDATE_LOCATION_IN_VEHICLE",0x80, null, allStates),
            new RegisteredPacket("TRADE_UPDATE",0x81, null, allStates),
            new RegisteredPacket("TRADE_PRESS_OTHER_OK",0x82, null, allStates),
            new RegisteredPacket("FRIEND_ADD_REQUEST",0x83, null, allStates),
            new RegisteredPacket("LOG_OUT_OK",0x84, null, allStates),
            new RegisteredPacket("ABNORMAL_STATUS_UPDATE",0x85, null, allStates),
            new RegisteredPacket("QUEST_LIST",0x86, null, allStates),
            new RegisteredPacket("ENCHANT_RESULT",0x87, null, allStates),
            new RegisteredPacket("PLEDGE_SHOW_MEMBER_LIST_DELETE_ALL",0x88, null, allStates),
            new RegisteredPacket("PLEDGE_INFO",0x89, null, allStates),
            new RegisteredPacket("PLEDGE_EXTENDED_INFO",0x8A, null, allStates),
            new RegisteredPacket("SUMMON_INFO",0x8B, null, allStates),
            new RegisteredPacket("RIDE",0x8C, null, allStates),
            new RegisteredPacket("DUMMY2",0x8D, null, allStates),
            new RegisteredPacket("PLEDGE_SHOW_INFO_UPDATE",0x8E, null, allStates),
            new RegisteredPacket("CLIENT_ACTION",0x8F, null, allStates),
            new RegisteredPacket("ACQUIRE_SKILL_LIST",0x90, null, allStates),
            new RegisteredPacket("ACQUIRE_SKILL_INFO",0x91, null, allStates),
            new RegisteredPacket("SERVER_OBJECT_INFO",0x92, null, allStates),
            new RegisteredPacket("GM_HIDE",0x93, null, allStates),
            new RegisteredPacket("ACQUIRE_SKILL_DONE",0x94, null, allStates),
            new RegisteredPacket("GM_VIEW_CHARACTER_INFO",0x95, null, allStates),
            new RegisteredPacket("GM_VIEW_PLEDGE_INFO",0x96, null, allStates),
            new RegisteredPacket("GM_VIEW_SKILL_INFO",0x97, null, allStates),
            new RegisteredPacket("GM_VIEW_MAGIC_INFO",0x98, null, allStates),
            new RegisteredPacket("GM_VIEW_QUEST_INFO",0x99, null, allStates),
            new RegisteredPacket("GM_VIEW_ITEM_LIST",0x9A, null, allStates),
            new RegisteredPacket("GM_VIEW_WAREHOUSE_WITHDRAW_LIST",0x9B, null, allStates),
            new RegisteredPacket("LIST_PARTY_WATING",0x9C, null, allStates),
            new RegisteredPacket("PARTY_ROOM_INFO",0x9D, null, allStates),
            new RegisteredPacket("PLAY_SOUND",0x9E, null, allStates),
            new RegisteredPacket("STATIC_OBJECT",0x9F, null, allStates),
            new RegisteredPacket("PRIVATE_STORE_MANAGE_LIST",0xA0, null, allStates),
            new RegisteredPacket("PRIVATE_STORE_LIST",0xA1, null, allStates),
            new RegisteredPacket("PRIVATE_STORE_MSG",0xA2, null, allStates),
            new RegisteredPacket("SHOW_MINIMAP",0xA3, null, allStates),
            new RegisteredPacket("REVIVE_REQUEST",0xA4, null, allStates),
            new RegisteredPacket("ABNORMAL_VISUAL_EFFECT",0xA5, null, allStates),
            new RegisteredPacket("TUTORIAL_SHOW_HTML",0xA6, null, allStates),
            new RegisteredPacket("TUTORIAL_SHOW_QUESTION_MARK",0xA7, null, allStates),
            new RegisteredPacket("TUTORIAL_ENABLE_CLIENT_EVENT",0xA8, null, allStates),
            new RegisteredPacket("TUTORIAL_CLOSE_HTML",0xA9, null, allStates),
            new RegisteredPacket("SHOW_RADAR",0xAA, null, allStates),
            new RegisteredPacket("WITHDRAW_ALLIANCE",0xAB, null, allStates),
            new RegisteredPacket("OUST_ALLIANCE_MEMBER_PLEDGE",0xAC, null, allStates),
            new RegisteredPacket("DISMISS_ALLIANCE",0xAD, null, allStates),
            new RegisteredPacket("SET_ALLIANCE_CREST",0xAE, null, allStates),
            new RegisteredPacket("ALLIANCE_CREST",0xAF, null, allStates),
            new RegisteredPacket("SERVER_CLOSE_SOCKET",0xB0, null, allStates),
            new RegisteredPacket("PET_STATUS_SHOW",0xB1, null, allStates),
            new RegisteredPacket("PET_INFO",0xB2, null, allStates),
            new RegisteredPacket("PET_ITEM_LIST",0xB3, null, allStates),
            new RegisteredPacket("PET_INVENTORY_UPDATE",0xB4, null, allStates),
            new RegisteredPacket("ALLIANCE_INFO",0xB5, null, allStates),
            new RegisteredPacket("PET_STATUS_UPDATE",0xB6, null, allStates),
            new RegisteredPacket("PET_DELETE",0xB7, null, allStates),
            new RegisteredPacket("DELETE_RADAR",0xB8, null, allStates),
            new RegisteredPacket("MY_TARGET_SELECTED",0xB9, null, allStates),
            new RegisteredPacket("PARTY_MEMBER_POSITION",0xBA, null, allStates),
            new RegisteredPacket("ASK_JOIN_ALLIANCE",0xBB, null, allStates),
            new RegisteredPacket("JOIN_ALLIANCE",0xBC, null, allStates),
            new RegisteredPacket("PRIVATE_STORE_BUY_MANAGE_LIST",0xBD, null, allStates),
            new RegisteredPacket("PRIVATE_STORE_BUY_LIST",0xBE, null, allStates),
            new RegisteredPacket("PRIVATE_STORE_BUY_MSG",0xBF, null, allStates),
            new RegisteredPacket("VEHICLE_START",0xC0, null, allStates),
            new RegisteredPacket("NPC_INFO_STATE",0xC1, null, allStates),
            new RegisteredPacket("START_ALLIANCE_WAR",0xC2, null, allStates),
            new RegisteredPacket("REPLY_START_ALLIANCE_WAR",0xC3, null, allStates),
            new RegisteredPacket("STOP_ALLIANCE_WAR",0xC4, null, allStates),
            new RegisteredPacket("REPLY_STOP_ALLIANCE_WAR",0xC5, null, allStates),
            new RegisteredPacket("SURRENDER_ALLIANCE_WAR",0xC6, null, allStates),
            new RegisteredPacket("SKILL_COOL_TIME",0xC7, null, allStates),
            new RegisteredPacket("PACKAGE_TO_LIST",0xC8, null, allStates),
            new RegisteredPacket("CASTLE_SIEGE_INFO",0xC9, null, allStates),
            new RegisteredPacket("CASTLE_SIEGE_ATTACKER_LIST",0xCA, null, allStates),
            new RegisteredPacket("CASTLE_SIEGE_DEFENDER_LIST",0xCB, null, allStates),
            new RegisteredPacket("NICK_NAME_CHANGED",0xCC, null, allStates),
            new RegisteredPacket("PLEDGE_STATUS_CHANGED",0xCD, null, allStates),
            new RegisteredPacket("RELATION_CHANGED",0xCE, null, allStates),
            new RegisteredPacket("EVENT_TRIGGER",0xCF, null, allStates),
            new RegisteredPacket("MULTI_SELL_LIST",0xD0, null, allStates),
            new RegisteredPacket("SET_SUMMON_REMAIN_TIME",0xD1, null, allStates),
            new RegisteredPacket("PACKAGE_SENDABLE_LIST",0xD2, null, allStates),
            new RegisteredPacket("EARTHQUAKE",0xD3, null, allStates),
            new RegisteredPacket("FLY_TO_LOCATION",0xD4, null, allStates),
            new RegisteredPacket("BLOCK_LIST",0xD5, null, allStates),
            new RegisteredPacket("SPECIAL_CAMERA",0xD6, null, allStates),
            new RegisteredPacket("NORMAL_CAMERA",0xD7, null, allStates),
            new RegisteredPacket("SKILL_REMAIN_SEC",0xD8, null, allStates),
            new RegisteredPacket("NET_PING",0xD9, new Ping(), allStates),
            new RegisteredPacket("DICE",0xDA, null, allStates),
            new RegisteredPacket("SNOOP",0xDB, null, allStates),
            new RegisteredPacket("RECIPE_BOOK_ITEM_LIST",0xDC, null, allStates),
            new RegisteredPacket("RECIPE_ITEM_MAKE_INFO",0xDD, null, allStates),
            new RegisteredPacket("RECIPE_SHOP_MANAGE_LIST",0xDE, null, allStates),
            new RegisteredPacket("RECIPE_SHOP_SELL_LIST",0xDF, null, allStates),
            new RegisteredPacket("RECIPE_SHOP_ITEM_INFO",0xE0, null, allStates),
            new RegisteredPacket("RECIPE_SHOP_MSG",0xE1, null, allStates),
            new RegisteredPacket("SHOW_CALC",0xE2, null, allStates),
            new RegisteredPacket("MON_RACE_INFO",0xE3, null, allStates),
            new RegisteredPacket("HENNA_ITEM_INFO",0xE4, null, allStates),
            new RegisteredPacket("HENNA_INFO",0xE5, null, allStates),
            new RegisteredPacket("HENNA_UNEQUIP_LIST",0xE6, null, allStates),
            new RegisteredPacket("HENNA_UNEQUIP_INFO",0xE7, null, allStates),
            new RegisteredPacket("MACRO_LIST",0xE8, null, allStates),
            new RegisteredPacket("BUY_LIST_SEED",0xE9, null, allStates),
            new RegisteredPacket("SHOW_TOWN_MAP",0xEA, null, allStates),
            new RegisteredPacket("OBSERVER_START",0xEB, null, allStates),
            new RegisteredPacket("OBSERVER_END",0xEC, null, allStates),
            new RegisteredPacket("CHAIR_SIT",0xED, null, allStates),
            new RegisteredPacket("HENNA_EQUIP_LIST",0xEE, null, allStates),
            new RegisteredPacket("SELL_LIST_PROCURE",0xEF, null, allStates),
            new RegisteredPacket("GMHENNA_INFO",0xF0, null, allStates),
            new RegisteredPacket("RADAR_CONTROL",0xF1, null, allStates),
            new RegisteredPacket("CLIENT_SET_TIME",0xF2, null, allStates),
            new RegisteredPacket("CONFIRM_DLG",0xF3, null, allStates),
            new RegisteredPacket("PARTY_SPELLED",0xF4, null, allStates),
            new RegisteredPacket("SHOP_PREVIEW_LIST",0xF5, null, allStates),
            new RegisteredPacket("SHOP_PREVIEW_INFO",0xF6, null, allStates),
            new RegisteredPacket("CAMERA_MODE",0xF7, null, allStates),
            new RegisteredPacket("SHOW_XMAS_SEAL",0xF8, null, allStates),
            new RegisteredPacket("ETC_STATUS_UPDATE",0xF9, null, allStates),
            new RegisteredPacket("SHORT_BUFF_STATUS_UPDATE",0xFA, null, allStates),
            new RegisteredPacket("SSQ_STATUS",0xFB, null, allStates),
            new RegisteredPacket("PETITION_VOTE",0xFC, null, allStates),
            new RegisteredPacket("AGIT_DECO_INFO",0xFD, null, allStates),
            new RegisteredPacket("DUMMY3",0xFE, null, allStates),
            // ExPackets
            new RegisteredPacket("EX_DUMMY",0xFE, 0x00, null, allStates),
            new RegisteredPacket("EX_REGEN_MAX",0xFE, 0x01, null, allStates),
            new RegisteredPacket("EX_EVENT_MATCH_USER_INFO",0xFE, 0x02, null, allStates),
            new RegisteredPacket("EX_COLOSSEUM_FENCE_INFO",0xFE, 0x03, null, allStates),
            new RegisteredPacket("EX_EVENT_MATCH_SPELLED_INFO",0xFE, 0x04, null, allStates),
            new RegisteredPacket("EX_EVENT_MATCH_FIRECRACKER",0xFE, 0x05, null, allStates),
            new RegisteredPacket("EX_EVENT_MATCH_TEAM_UNLOCKED",0xFE, 0x06, null, allStates),
            new RegisteredPacket("EX_EVENT_MATCH_GMTEST",0xFE, 0x07, null, allStates),
            new RegisteredPacket("EX_PARTY_ROOM_MEMBER",0xFE, 0x08, null, allStates),
            new RegisteredPacket("EX_CLOSE_PARTY_ROOM",0xFE, 0x09, null, allStates),
            new RegisteredPacket("EX_MANAGE_PARTY_ROOM_MEMBER",0xFE, 0x0A, null, allStates),
            new RegisteredPacket("EX_EVENT_MATCH_LOCK_RESULT",0xFE, 0x0B, null, allStates),
            new RegisteredPacket("EX_AUTO_SOUL_SHOT",0xFE, 0x0C, null, allStates),
            new RegisteredPacket("EX_EVENT_MATCH_LIST",0xFE, 0x0D, null, allStates),
            new RegisteredPacket("EX_EVENT_MATCH_OBSERVER",0xFE, 0x0E, null, allStates),
            new RegisteredPacket("EX_EVENT_MATCH_MESSAGE",0xFE, 0x0F, null, allStates),
            new RegisteredPacket("EX_EVENT_MATCH_SCORE",0xFE, 0x10, null, allStates),
            new RegisteredPacket("EX_SERVER_PRIMITIVE",0xFE, 0x11, null, allStates),
            new RegisteredPacket("EX_OPEN_MPCC",0xFE, 0x12, null, allStates),
            new RegisteredPacket("EX_CLOSE_MPCC",0xFE, 0x13, null, allStates),
            new RegisteredPacket("EX_SHOW_CASTLE_INFO",0xFE, 0x14, null, allStates),
            new RegisteredPacket("EX_SHOW_FORTRESS_INFO",0xFE, 0x15, null, allStates),
            new RegisteredPacket("EX_SHOW_AGIT_INFO",0xFE, 0x16, null, allStates),
            new RegisteredPacket("EX_SHOW_FORTRESS_SIEGE_INFO",0xFE, 0x17, null, allStates),
            new RegisteredPacket("EX_PARTY_PET_WINDOW_ADD",0xFE, 0x18, null, allStates),
            new RegisteredPacket("EX_PARTY_PET_WINDOW_UPDATE",0xFE, 0x19, null, allStates),
            new RegisteredPacket("EX_ASK_JOIN_MPCC",0xFE, 0x1A, null, allStates),
            new RegisteredPacket("EX_PLEDGE_EMBLEM",0xFE, 0x1B, null, allStates),
            new RegisteredPacket("EX_EVENT_MATCH_TEAM_INFO",0xFE, 0x1C, null, allStates),
            new RegisteredPacket("EX_EVENT_MATCH_CREATE",0xFE, 0x1D, null, allStates),
            new RegisteredPacket("EX_FISHING_START",0xFE, 0x1E, null, allStates),
            new RegisteredPacket("EX_FISHING_END",0xFE, 0x1F, null, allStates),
            new RegisteredPacket("EX_SHOW_QUEST_INFO",0xFE, 0x20, null, allStates),
            new RegisteredPacket("EX_SHOW_QUEST_MARK",0xFE, 0x21, null, allStates),
            new RegisteredPacket("EX_SEND_MANOR_LIST",0xFE, 0x22, null, allStates),
            new RegisteredPacket("EX_SHOW_SEED_INFO",0xFE, 0x23, null, allStates),
            new RegisteredPacket("EX_SHOW_CROP_INFO",0xFE, 0x24, null, allStates),
            new RegisteredPacket("EX_SHOW_MANOR_DEFAULT_INFO",0xFE, 0x25, null, allStates),
            new RegisteredPacket("EX_SHOW_SEED_SETTING",0xFE, 0x26, null, allStates),
            new RegisteredPacket("EX_FISHING_START_COMBAT",0xFE, 0x27, null, allStates),
            new RegisteredPacket("EX_FISHING_HP_REGEN",0xFE, 0x28, null, allStates),
            new RegisteredPacket("EX_ENCHANT_SKILL_LIST",0xFE, 0x29, null, allStates),
            new RegisteredPacket("EX_ENCHANT_SKILL_INFO",0xFE, 0x2A, null, allStates),
            new RegisteredPacket("EX_SHOW_CROP_SETTING",0xFE, 0x2B, null, allStates),
            new RegisteredPacket("EX_SHOW_SELL_CROP_LIST",0xFE, 0x2C, null, allStates),
            new RegisteredPacket("EX_OLYMPIAD_MATCH_END",0xFE, 0x2D, null, allStates),
            new RegisteredPacket("EX_MAIL_ARRIVED",0xFE, 0x2E, null, allStates),
            new RegisteredPacket("EX_STORAGE_MAX_COUNT",0xFE, 0x2F, null, allStates),
            new RegisteredPacket("EX_EVENT_MATCH_MANAGE",0xFE, 0x30, null, allStates),
            new RegisteredPacket("EX_MULTI_PARTY_COMMAND_CHANNEL_INFO",0xFE, 0x31, null, allStates),
            new RegisteredPacket("EX_PCCAFE_POINT_INFO",0xFE, 0x32, null, allStates),
            new RegisteredPacket("EX_SET_COMPASS_ZONE_CODE",0xFE, 0x33, null, allStates),
            new RegisteredPacket("EX_GET_BOSS_RECORD",0xFE, 0x34, null, allStates),
            new RegisteredPacket("EX_ASK_JOIN_PARTY_ROOM",0xFE, 0x35, null, allStates),
            new RegisteredPacket("EX_LIST_PARTY_MATCHING_WAITING_ROOM",0xFE, 0x36, null, allStates),
            new RegisteredPacket("EX_SET_MPCC_ROUTING",0xFE, 0x37, null, allStates),
            new RegisteredPacket("EX_SHOW_ADVENTURER_GUIDE_BOOK",0xFE, 0x38, null, allStates),
            new RegisteredPacket("EX_SHOW_SCREEN_MESSAGE",0xFE, 0x39, null, allStates),
            new RegisteredPacket("PLEDGE_SKILL_LIST",0xFE, 0x3A, null, allStates),
            new RegisteredPacket("PLEDGE_SKILL_LIST_ADD",0xFE, 0x3B, null, allStates),
            new RegisteredPacket("PLEDGE_SKILL_LIST_REMOVE",0xFE, 0x3C, null, allStates),
            new RegisteredPacket("PLEDGE_POWER_GRADE_LIST",0xFE, 0x3D, null, allStates),
            new RegisteredPacket("PLEDGE_RECEIVE_POWER_INFO",0xFE, 0x3E, null, allStates),
            new RegisteredPacket("PLEDGE_RECEIVE_MEMBER_INFO",0xFE, 0x3F, null, allStates),
            new RegisteredPacket("PLEDGE_RECEIVE_WAR_LIST",0xFE, 0x40, null, allStates),
            new RegisteredPacket("PLEDGE_RECEIVE_SUB_PLEDGE_CREATED",0xFE, 0x41, null, allStates),
            new RegisteredPacket("EX_RED_SKY",0xFE, 0x42, null, allStates),
            new RegisteredPacket("PLEDGE_RECEIVE_UPDATE_POWER",0xFE, 0x43, null, allStates),
            new RegisteredPacket("FLY_SELF_DESTINATION",0xFE, 0x44, null, allStates),
            new RegisteredPacket("SHOW_PCCAFE_COUPON_SHOW_UI",0xFE, 0x45, null, allStates),
            new RegisteredPacket("EX_SEARCH_ORC",0xFE, 0x46, null, allStates),
            new RegisteredPacket("EX_CURSED_WEAPON_LIST",0xFE, 0x47, null, allStates),
            new RegisteredPacket("EX_CURSED_WEAPON_LOCATION",0xFE, 0x48, null, allStates),
            new RegisteredPacket("EX_RESTART_CLIENT",0xFE, 0x49, null, allStates),
            new RegisteredPacket("EX_REQUEST_HACK_SHIELD",0xFE, 0x4A, null, allStates),
            new RegisteredPacket("EX_USE_SHARED_GROUP_ITEM",0xFE, 0x4B, null, allStates),
            new RegisteredPacket("EX_MPCCSHOW_PARTY_MEMBER_INFO",0xFE, 0x4C, null, allStates),
            new RegisteredPacket("EX_DUEL_ASK_START",0xFE, 0x4D, null, allStates),
            new RegisteredPacket("EX_DUEL_READY",0xFE, 0x4E, null, allStates),
            new RegisteredPacket("EX_DUEL_START",0xFE, 0x4F, null, allStates),
            new RegisteredPacket("EX_DUEL_END",0xFE, 0x50, null, allStates),
            new RegisteredPacket("EX_DUEL_UPDATE_USER_INFO",0xFE, 0x51, null, allStates),
            new RegisteredPacket("EX_SHOW_VARIATION_MAKE_WINDOW",0xFE, 0x52, null, allStates),
            new RegisteredPacket("EX_SHOW_VARIATION_CANCEL_WINDOW",0xFE, 0x53, null, allStates),
            new RegisteredPacket("EX_PUT_ITEM_RESULT_FOR_VARIATION_MAKE",0xFE, 0x54, null, allStates),
            new RegisteredPacket("EX_PUT_INTENSIVE_RESULT_FOR_VARIATION_MAKE",0xFE, 0x55, null, allStates),
            new RegisteredPacket("EX_PUT_COMMISSION_RESULT_FOR_VARIATION_MAKE",0xFE, 0x56, null, allStates),
            new RegisteredPacket("EX_VARIATION_RESULT",0xFE, 0x57, null, allStates),
            new RegisteredPacket("EX_PUT_ITEM_RESULT_FOR_VARIATION_CANCEL",0xFE, 0x58, null, allStates),
            new RegisteredPacket("EX_VARIATION_CANCEL_RESULT",0xFE, 0x59, null, allStates),
            new RegisteredPacket("EX_DUEL_ENEMY_RELATION",0xFE, 0x5A, null, allStates),
            new RegisteredPacket("EX_PLAY_ANIMATION",0xFE, 0x5B, null, allStates),
            new RegisteredPacket("EX_MPCCPARTY_INFO_UPDATE",0xFE, 0x5C, null, allStates),
            new RegisteredPacket("EX_PLAY_SCENE",0xFE, 0x5D, null, allStates),
            new RegisteredPacket("EX_SPAWN_EMITTER",0xFE, 0x5E, null, allStates),
            new RegisteredPacket("EX_ENCHANT_SKILL_INFO_DETAIL",0xFE, 0x5F, null, allStates),
            new RegisteredPacket("EX_BASIC_ACTION_LIST",0xFE, 0x60, null, allStates),
            new RegisteredPacket("EX_AIR_SHIP_INFO",0xFE, 0x61, null, allStates),
            new RegisteredPacket("EX_ATTRIBUTE_ENCHANT_RESULT",0xFE, 0x62, null, allStates),
            new RegisteredPacket("EX_CHOOSE_INVENTORY_ATTRIBUTE_ITEM",0xFE, 0x63, null, allStates),
            new RegisteredPacket("EX_GET_ON_AIR_SHIP",0xFE, 0x64, null, allStates),
            new RegisteredPacket("EX_GET_OFF_AIR_SHIP",0xFE, 0x65, null, allStates),
            new RegisteredPacket("EX_MOVE_TO_LOCATION_AIR_SHIP",0xFE, 0x66, null, allStates),
            new RegisteredPacket("EX_STOP_MOVE_AIR_SHIP",0xFE, 0x67, null, allStates),
            new RegisteredPacket("EX_SHOW_TRACE",0xFE, 0x68, null, allStates),
            new RegisteredPacket("EX_ITEM_AUCTION_INFO",0xFE, 0x69, null, allStates),
            new RegisteredPacket("EX_NEED_TO_CHANGE_NAME",0xFE, 0x6A, null, allStates),
            new RegisteredPacket("EX_PARTY_PET_WINDOW_DELETE",0xFE, 0x6B, null, allStates),
            new RegisteredPacket("EX_TUTORIAL_LIST",0xFE, 0x6C, null, allStates),
            new RegisteredPacket("EX_RP_ITEM_LINK",0xFE, 0x6D, null, allStates),
            new RegisteredPacket("EX_MOVE_TO_LOCATION_IN_AIR_SHIP",0xFE, 0x6E, null, allStates),
            new RegisteredPacket("EX_STOP_MOVE_IN_AIR_SHIP",0xFE, 0x6F, null, allStates),
            new RegisteredPacket("EX_VALIDATE_LOCATION_IN_AIR_SHIP",0xFE, 0x70, null, allStates),
            new RegisteredPacket("EX_UI_SETTING",0xFE, 0x71, null, allStates),
            new RegisteredPacket("EX_MOVE_TO_TARGET_IN_AIR_SHIP",0xFE, 0x72, null, allStates),
            new RegisteredPacket("EX_ATTACK_IN_AIR_SHIP",0xFE, 0x73, null, allStates),
            new RegisteredPacket("EX_MAGIC_SKILL_USE_IN_AIR_SHIP",0xFE, 0x74, null, allStates),
            new RegisteredPacket("EX_SHOW_BASE_ATTRIBUTE_CANCEL_WINDOW",0xFE, 0x75, null, allStates),
            new RegisteredPacket("EX_BASE_ATTRIBUTE_CANCEL_RESULT",0xFE, 0x76, null, allStates),
            new RegisteredPacket("EX_SUB_PLEDGET_SKILL_ADD",0xFE, 0x77, null, allStates),
            new RegisteredPacket("EX_RESPONSE_FREE_SERVER",0xFE, 0x78, null, allStates),
            new RegisteredPacket("EX_SHOW_PROCURE_CROP_DETAIL",0xFE, 0x79, null, allStates),
            new RegisteredPacket("EX_HERO_LIST",0xFE, 0x7A, null, allStates),
            new RegisteredPacket("EX_OLYMPIAD_USER_INFO",0xFE, 0x7B, null, allStates),
            new RegisteredPacket("EX_OLYMPIAD_SPELLED_INFO",0xFE, 0x7C, null, allStates),
            new RegisteredPacket("EX_OLYMPIAD_MODE",0xFE, 0x7D, null, allStates),
            new RegisteredPacket("EX_SHOW_FORTRESS_MAP_INFO",0xFE, 0x7E, null, allStates),
            new RegisteredPacket("EX_PVP_MATCH_RECORD",0xFE, 0x7F, null, allStates),
            new RegisteredPacket("EX_PVP_MATCH_USER_DIE",0xFE, 0x80, null, allStates),
            new RegisteredPacket("EX_PRIVATE_STORE_WHOLE_MSG",0xFE, 0x81, null, allStates),
            new RegisteredPacket("EX_PUT_ENCHANT_TARGET_ITEM_RESULT",0xFE, 0x82, null, allStates),
            new RegisteredPacket("EX_PUT_ENCHANT_SUPPORT_ITEM_RESULT",0xFE, 0x83, null, allStates),
            new RegisteredPacket("EX_CHANGE_NICKNAME_NCOLOR",0xFE, 0x84, null, allStates),
            new RegisteredPacket("EX_GET_BOOK_MARK_INFO",0xFE, 0x85, null, allStates),
            new RegisteredPacket("EX_NOTIFY_PREMIUM_ITEM",0xFE, 0x86, null, allStates),
            new RegisteredPacket("EX_GET_PREMIUM_ITEM_LIST",0xFE, 0x87, null, allStates),
            new RegisteredPacket("EX_PERIODIC_ITEM_LIST",0xFE, 0x88, null, allStates),
            new RegisteredPacket("EX_JUMP_TO_LOCATION",0xFE, 0x89, null, allStates),
            new RegisteredPacket("EX_PVP_MATCH_CCRECORD",0xFE, 0x8A, null, allStates),
            new RegisteredPacket("EX_PVP_MATCH_CCMY_RECORD",0xFE, 0x8B, null, allStates),
            new RegisteredPacket("EX_PVP_MATCH_CCRETIRE",0xFE, 0x8C, null, allStates),
            new RegisteredPacket("EX_SHOW_TERRITORY",0xFE, 0x8D, null, allStates),
            new RegisteredPacket("EX_NPC_QUEST_HTML_MESSAGE",0xFE, 0x8E, null, allStates),
            new RegisteredPacket("EX_SEND_UIEVENT",0xFE, 0x8F, null, allStates),
            new RegisteredPacket("EX_NOTIFY_BIRTH_DAY",0xFE, 0x90, null, allStates),
            new RegisteredPacket("EX_SHOW_DOMINION_REGISTRY",0xFE, 0x91, null, allStates),
            new RegisteredPacket("EX_REPLY_REGISTER_DOMINION",0xFE, 0x92, null, allStates),
            new RegisteredPacket("EX_REPLY_DOMINION_INFO",0xFE, 0x93, null, allStates),
            new RegisteredPacket("EX_SHOW_OWNTHING_POS",0xFE, 0x94, null, allStates),
            new RegisteredPacket("EX_CLEFT_LIST",0xFE, 0x95, null, allStates),
            new RegisteredPacket("EX_CLEFT_STATE",0xFE, 0x96, null, allStates),
            new RegisteredPacket("EX_DOMINION_CHANNEL_SET",0xFE, 0x97, null, allStates),
            new RegisteredPacket("EX_BLOCK_UP_SET_LIST",0xFE, 0x98, null, allStates),
            new RegisteredPacket("EX_BLOCK_UP_SET_STATE",0xFE, 0x99, null, allStates),
            new RegisteredPacket("EX_START_SCENE_PLAYER",0xFE, 0x9A, null, allStates),
            new RegisteredPacket("EX_AIR_SHIP_TELEPORT_LIST",0xFE, 0x9B, null, allStates),
            new RegisteredPacket("EX_MPCC_ROOM_INFO",0xFE, 0x9C, null, allStates),
            new RegisteredPacket("EX_LIST_MPCC_WAITING",0xFE, 0x9D, null, allStates),
            new RegisteredPacket("EX_DISSMISS_MPCC_ROOM",0xFE, 0x9E, null, allStates),
            new RegisteredPacket("EX_MANAGE_MPCC_ROOM_MEMBER",0xFE, 0x9F, null, allStates),
            new RegisteredPacket("EX_MPCC_ROOM_MEMBER",0xFE, 0xA0, null, allStates),
            new RegisteredPacket("EX_VITALITY_POINT_INFO",0xFE, 0xA1, null, allStates),
            new RegisteredPacket("EX_SHOW_SEED_MAP_INFO",0xFE, 0xA2, null, allStates),
            new RegisteredPacket("EX_MPCC_PARTYMASTER_LIST",0xFE, 0xA3, null, allStates),
            new RegisteredPacket("EX_DOMINION_WAR_START",0xFE, 0xA4, null, allStates),
            new RegisteredPacket("EX_DOMINION_WAR_END",0xFE, 0xA5, null, allStates),
            new RegisteredPacket("EX_SHOW_LINES",0xFE, 0xA6, null, allStates),
            new RegisteredPacket("EX_PARTY_MEMBER_RENAMED",0xFE, 0xA7, null, allStates),
            new RegisteredPacket("EX_ENCHANT_SKILL_RESULT",0xFE, 0xA8, null, allStates),
            new RegisteredPacket("EX_REFUND_LIST",0xFE, 0xA9, null, allStates),
            new RegisteredPacket("EX_NOTICE_POST_ARRIVED",0xFE, 0xAA, null, allStates),
            new RegisteredPacket("EX_SHOW_RECEIVED_POST_LIST",0xFE, 0xAB, null, allStates),
            new RegisteredPacket("EX_REPLY_RECEIVED_POST",0xFE, 0xAC, null, allStates),
            new RegisteredPacket("EX_SHOW_SENT_POST_LIST",0xFE, 0xAD, null, allStates),
            new RegisteredPacket("EX_REPLY_SENT_POST",0xFE, 0xAE, null, allStates),
            new RegisteredPacket("EX_RESPONSE_SHOW_STEP_ONE",0xFE, 0xAF, null, allStates),
            new RegisteredPacket("EX_RESPONSE_SHOW_STEP_TWO",0xFE, 0xB0, null, allStates),
            new RegisteredPacket("EX_RESPONSE_SHOW_CONTENTS",0xFE, 0xB1, null, allStates),
            new RegisteredPacket("EX_SHOW_PETITION_HTML",0xFE, 0xB2, null, allStates),
            new RegisteredPacket("EX_REPLY_POST_ITEM_LIST",0xFE, 0xB3, null, allStates),
            new RegisteredPacket("EX_CHANGE_POST_STATE",0xFE, 0xB4, null, allStates),
            new RegisteredPacket("EX_REPLY_WRITE_POST",0xFE, 0xB5, null, allStates),
            new RegisteredPacket("EX_INITIALIZE_SEED",0xFE, 0xB6, null, allStates),
            new RegisteredPacket("EX_RAID_RESERVE_RESULT",0xFE, 0xB7, null, allStates),
            new RegisteredPacket("EX_BUY_SELL_LIST",0xFE, 0xB8, null, allStates),
            new RegisteredPacket("EX_CLOSE_RAID_SOCKET",0xFE, 0xB9, null, allStates),
            new RegisteredPacket("EX_PRIVATE_MARKET_LIST",0xFE, 0xBA, null, allStates),
            new RegisteredPacket("EX_RAID_CHARACTER_SELECTED",0xFE, 0xBB, null, allStates),
            new RegisteredPacket("EX_ASK_COUPLE_ACTION",0xFE, 0xBC, null, allStates),
            new RegisteredPacket("EX_BR_BROADCAST_EVENT_STATE",0xFE, 0xBD, null, allStates),
            new RegisteredPacket("EX_BR_LOAD_EVENT_TOP_RANKERS",0xFE, 0xBE, null, allStates),
            new RegisteredPacket("EX_CHANGE_NPC_STATE",0xFE, 0xBF, null, allStates),
            new RegisteredPacket("EX_ASK_MODIFY_PARTY_LOOTING",0xFE, 0xC0, null, allStates),
            new RegisteredPacket("EX_SET_PARTY_LOOTING",0xFE, 0xC1, null, allStates),
            new RegisteredPacket("EX_ROTATION",0xFE, 0xC2, null, allStates),
            new RegisteredPacket("EX_CHANGE_CLIENT_EFFECT_INFO",0xFE, 0xC3, null, allStates),
            new RegisteredPacket("EX_MEMBERSHIP_INFO",0xFE, 0xC4, null, allStates),
            new RegisteredPacket("EX_REPLY_HAND_OVER_PARTY_MASTER",0xFE, 0xC5, null, allStates),
            new RegisteredPacket("EX_QUEST_NPC_LOG_LIST",0xFE, 0xC6, null, allStates),
            new RegisteredPacket("EX_QUEST_ITEM_LIST",0xFE, 0xC7, null, allStates),
            new RegisteredPacket("EX_GM_VIEW_QUEST_ITEM_LIST",0xFE, 0xC8, null, allStates),
            new RegisteredPacket("EX_RESTART_RESPONSE",0xFE, 0xC9, null, allStates),
            new RegisteredPacket("EX_VOTE_SYSTEM_INFO",0xFE, 0xCA, null, allStates),
            new RegisteredPacket("EX_SHUTTLE_INFO",0xFE, 0xCB, null, allStates),
            new RegisteredPacket("EX_SUTTLE_GET_ON",0xFE, 0xCC, null, allStates),
            new RegisteredPacket("EX_SUTTLE_GET_OFF",0xFE, 0xCD, null, allStates),
            new RegisteredPacket("EX_SUTTLE_MOVE",0xFE, 0xCE, null, allStates),
            new RegisteredPacket("EX_MOVE_TO_LOCATION_IN_SUTTLE",0xFE, 0xCF, null, allStates),
            new RegisteredPacket("EX_STOP_MOVE_IN_SHUTTLE",0xFE, 0xD0, null, allStates),
            new RegisteredPacket("EX_VALIDATE_LOCATION_IN_SHUTTLE",0xFE, 0xD1, null, allStates),
            new RegisteredPacket("EX_AGIT_AUCTION_CMD",0xFE, 0xD2, null, allStates),
            new RegisteredPacket("EX_CONFIRM_ADDING_POST_FRIEND",0xFE, 0xD3, null, allStates),
            new RegisteredPacket("EX_RECEIVE_SHOW_POST_FRIEND",0xFE, 0xD4, null, allStates),
            new RegisteredPacket("EX_RECEIVE_OLYMPIAD",0xFE, 0xD5, null, allStates),
            new RegisteredPacket("EX_BR_GAME_POINT",0xFE, 0xD6, null, allStates),
            new RegisteredPacket("EX_BR_PRODUCT_LIST",0xFE, 0xD7, null, allStates),
            new RegisteredPacket("EX_BR_PRODUCT_INFO",0xFE, 0xD8, null, allStates),
            new RegisteredPacket("EX_BR_BUY_PRODUCT",0xFE, 0xD9, null, allStates),
            new RegisteredPacket("EX_BR_PREMIUM_STATE",0xFE, 0xDA, null, allStates),
            new RegisteredPacket("EX_BR_EXTRA_USER_INFO",0xFE, 0xDB, null, allStates),
            new RegisteredPacket("EX_BR_BUFF_EVENT_STATE",0xFE, 0xDC, null, allStates),
            new RegisteredPacket("EX_BR_RECENT_PRODUCT_LIST",0xFE, 0xDD, null, allStates),
            new RegisteredPacket("EX_BR_MINIGAME_LOAD_SCORES",0xFE, 0xDE, null, allStates),
            new RegisteredPacket("EX_BR_AGATHION_ENERGY_INFO",0xFE, 0xDF, null, allStates),
            new RegisteredPacket("EX_SHOW_CHANNELING_EFFECT",0xFE, 0xE0, null, allStates),
            new RegisteredPacket("EX_GET_CRYSTALIZING_ESTIMATION",0xFE, 0xE1, null, allStates),
            new RegisteredPacket("EX_GET_CRYSTALIZING_FAIL",0xFE, 0xE2, null, allStates),
            new RegisteredPacket("EX_NAVIT_ADVENT_POINT_INFO",0xFE, 0xE3, null, allStates),
            new RegisteredPacket("EX_NAVIT_ADVENT_EFFECT",0xFE, 0xE4, null, allStates),
            new RegisteredPacket("EX_NAVIT_ADVENT_TIME_CHANGE",0xFE, 0xE5, null, allStates),
            new RegisteredPacket("EX_ABNORMAL_STATUS_UPDATE_FROM_TARGET",0xFE, 0xE6, null, allStates),
            new RegisteredPacket("EX_STOP_SCENE_PLAYER",0xFE, 0xE7, null, allStates),
            new RegisteredPacket("EX_FLY_MOVE",0xFE, 0xE8, null, allStates),
            new RegisteredPacket("EX_DYNAMIC_QUEST",0xFE, 0xE9, null, allStates),
            new RegisteredPacket("EX_SUBJOB_INFO",0xFE, 0xEA, null, allStates),
            new RegisteredPacket("EX_CHANGE_MPCOST",0xFE, 0xEB, null, allStates),
            new RegisteredPacket("EX_FRIEND_DETAIL_INFO",0xFE, 0xEC, null, allStates),
            new RegisteredPacket("EX_BLOCK_ADD_RESULT",0xFE, 0xED, null, allStates),
            new RegisteredPacket("EX_BLOCK_REMOVE_RESULT",0xFE, 0xEE, null, allStates),
            new RegisteredPacket("EX_BLOCK_DEFAIL_INFO",0xFE, 0xEF, null, allStates),
            new RegisteredPacket("EX_LOAD_INZONE_PARTY_HISTORY",0xFE, 0xF0, null, allStates),
            new RegisteredPacket("EX_FRIEND_NOTIFY_NAME_CHANGE",0xFE, 0xF1, null, allStates),
            new RegisteredPacket("EX_SHOW_COMMISSION",0xFE, 0xF2, null, allStates),
            new RegisteredPacket("EX_RESPONSE_COMMISSION_ITEM_LIST",0xFE, 0xF3, null, allStates),
            new RegisteredPacket("EX_RESPONSE_COMMISSION_INFO",0xFE, 0xF4, null, allStates),
            new RegisteredPacket("EX_RESPONSE_COMMISSION_REGISTER",0xFE, 0xF5, null, allStates),
            new RegisteredPacket("EX_RESPONSE_COMMISSION_DELETE",0xFE, 0xF6, null, allStates),
            new RegisteredPacket("EX_RESPONSE_COMMISSION_LIST",0xFE, 0xF7, null, allStates),
            new RegisteredPacket("EX_RESPONSE_COMMISSION_BUY_INFO",0xFE, 0xF8, null, allStates),
            new RegisteredPacket("EX_RESPONSE_COMMISSION_BUY_ITEM",0xFE, 0xF9, null, allStates),
            new RegisteredPacket("EX_ACQUIRABLE_SKILL_LIST_BY_CLASS",0xFE, 0xFA, null, allStates),
            new RegisteredPacket("EX_MAGIC_ATTACK_INFO",0xFE, 0xFB, null, allStates),
            new RegisteredPacket("EX_ACQUIRE_SKILL_INFO",0xFE, 0xFC, null, allStates),
            new RegisteredPacket("EX_NEW_SKILL_TO_LEARN_BY_LEVEL_UP",0xFE, 0xFD, null, allStates),
            new RegisteredPacket("EX_CALL_TO_CHANGE_CLASS",0xFE, 0xFE, null, allStates),
            new RegisteredPacket("EX_CHANGE_TO_AWAKENED_CLASS",0xFE, 0xFF, null, allStates),
            new RegisteredPacket("EX_TACTICAL_SIGN",0xFE, 0x100, null, allStates),
            new RegisteredPacket("EX_LOAD_STAT_WORLD_RANK",0xFE, 0x101, null, allStates),
            new RegisteredPacket("EX_LOAD_STAT_USER",0xFE, 0x102, null, allStates),
            new RegisteredPacket("EX_LOAD_STAT_HOT_LINK",0xFE, 0x103, null, allStates),
            new RegisteredPacket("EX_GET_WEB_SESSION_ID",0xFE, 0x104, null, allStates),
            new RegisteredPacket("EX_2ND_PASSWORD_CHECK",0xFE, 0x105, null, allStates),
            new RegisteredPacket("EX_2ND_PASSWORD_VERIFY",0xFE, 0x106, null, allStates),
            new RegisteredPacket("EX_2ND_PASSWORD_ACK",0xFE, 0x107, null, allStates),
            new RegisteredPacket("EX_FLY_MOVE_BROADCAST",0xFE, 0x108, null, allStates),
            new RegisteredPacket("EX_SHOW_USM",0xFE, 0x109, null, allStates),
            new RegisteredPacket("EX_SHOW_STAT_PAGE",0xFE, 0x10A, null, allStates),
            new RegisteredPacket("EX_IS_CHAR_NAME_CREATABLE",0xFE, 0x10B, null, allStates),
            new RegisteredPacket("EX_GOODS_INVENTORY_CHANGED_NOTI",0xFE, 0x10C, null, allStates),
            new RegisteredPacket("EX_GOODS_INVENTORY_INFO",0xFE, 0x10D, null, allStates),
            new RegisteredPacket("EX_GOODS_INVENTORY_RESULT",0xFE, 0x10E, null, allStates),
            new RegisteredPacket("EX_ALTER_SKILL_REQUEST",0xFE, 0x10F, null, allStates),
            new RegisteredPacket("EX_NOTIFY_FLY_MOVE_START",0xFE, 0x110, null, allStates),
            new RegisteredPacket("EX_DUMMY2",0xFE, 0x111, null, allStates),
            new RegisteredPacket("EX_CLOSE_COMMISSION",0xFE, 0x112, null, allStates),
            new RegisteredPacket("EX_CHANGE_ATTRIBUTE_ITEM_LIST",0xFE, 0x113, null, allStates),
            new RegisteredPacket("EX_CHANGE_ATTRIBUTE_INFO",0xFE, 0x114, null, allStates),
            new RegisteredPacket("EX_CHANGE_ATTRIBUTE_OK",0xFE, 0x115, null, allStates),
            new RegisteredPacket("EX_CHANGE_ATTRIBUTE_FAIL",0xFE, 0x116, null, allStates),
            new RegisteredPacket("EX_LIGHTING_CANDLE_EVENT",0xFE, 0x117, null, allStates),
            new RegisteredPacket("EX_VITALITY_EFFECT_INFO",0xFE, 0x118, null, allStates),
            new RegisteredPacket("EX_LOGIN_VITALITY_EFFECT_INFO",0xFE, 0x119, null, allStates),
            new RegisteredPacket("EX_BR_PRESENT_BUY_PRODUCT",0xFE, 0x11A, null, allStates),
            new RegisteredPacket("EX_MENTOR_LIST",0xFE, 0x11B, null, allStates),
            new RegisteredPacket("EX_MENTOR_ADD",0xFE, 0x11C, null, allStates),
            new RegisteredPacket("LIST_MENTEE_WAITING",0xFE, 0x11D, null, allStates),
            new RegisteredPacket("EX_INZONE_WAITING_INFO",0xFE, 0x11E, null, allStates),
            new RegisteredPacket("EX_CURIOUS_HOUSE_STATE",0xFE, 0x11F, null, allStates),
            new RegisteredPacket("EX_CURIOUS_HOUSE_ENTER",0xFE, 0x120, null, allStates),
            new RegisteredPacket("EX_CURIOUS_HOUSE_LEAVE",0xFE, 0x121, null, allStates),
            new RegisteredPacket("EX_CURIOUS_HOUSE_MEMBER_LIST",0xFE, 0x122, null, allStates),
            new RegisteredPacket("EX_CURIOUS_HOUSE_MEMBER_UPDATE",0xFE, 0x123, null, allStates),
            new RegisteredPacket("EX_CURIOUS_HOUSE_REMAIN_TIME",0xFE, 0x124, null, allStates),
            new RegisteredPacket("EX_CURIOUS_HOUSE_RESULT",0xFE, 0x125, null, allStates),
            new RegisteredPacket("EX_CURIOUS_HOUSE_OBSERVE_LIST",0xFE, 0x126, null, allStates),
            new RegisteredPacket("EX_CURIOUS_HOUSE_OBSERVE_MODE",0xFE, 0x127, null, allStates),
            new RegisteredPacket("EX_SYSSTRING",0xFE, 0x128, null, allStates),
            new RegisteredPacket("EX_CHOOSE_SHAPE_SHIFTING_ITEM",0xFE, 0x129, null, allStates),
            new RegisteredPacket("EX_PUT_SHAPE_SHIFTING_TARGET_ITEM_RESULT",0xFE, 0x12A, null, allStates),
            new RegisteredPacket("EX_PUT_SHAPE_SHIFTING_EXTRACTION_ITEM_RESULT",0xFE, 0x12B, null, allStates),
            new RegisteredPacket("EX_SHAPE_SHIFTING_RESULT",0xFE, 0x12C, null, allStates),
            new RegisteredPacket("EX_CASTLE_STATE",0xFE, 0x12D, null, allStates),
            new RegisteredPacket("EX_NCGUARD_RECEIVE_DATA_FROM_SERVER",0xFE, 0x12E, null, allStates),
            new RegisteredPacket("EX_KALIE_EVENT",0xFE, 0x12F, null, allStates),
            new RegisteredPacket("EX_KALIE_EVENT_JACKPOT_USER",0xFE, 0x130, null, allStates),
            new RegisteredPacket("EX_ABNORMAL_VISUAL_EFFECT_INFO",0xFE, 0x131, null, allStates),
            new RegisteredPacket("EX_NPC_INFO_SPEED",0xFE, 0x132, null, allStates),
            new RegisteredPacket("EX_SET_PLEDGE_EMBLEM_ACK",0xFE, 0x133, null, allStates),
            new RegisteredPacket("EX_SHOW_BEAUTY_MENU",0xFE, 0x134, null, allStates),
            new RegisteredPacket("EX_RESPONSE_BEAUTY_LIST",0xFE, 0x135, null, allStates),
            new RegisteredPacket("EX_RESPONSE_BEAUTY_REGIST_RESET",0xFE, 0x136, null, allStates),
            new RegisteredPacket("EX_RESPONSE_RESET_LIST",0xFE, 0x137, null, allStates),
            new RegisteredPacket("EX_SHUFFLE_SEED_AND_PUBLIC_KEY",0xFE, 0x138, null, allStates),
            new RegisteredPacket("EX_CHECK_SPEED_HACK",0xFE, 0x139, null, allStates),
            new RegisteredPacket("EX_BR_NEW_ICON_CASH_BTN_WND",0xFE, 0x13A, null, allStates),
            new RegisteredPacket("EX_EVENT_CAMPAIGN_INFO",0xFE, 0x13B, null, allStates),
            new RegisteredPacket("EX_UN_READ_MAIL_COUNT",0xFE, 0x13C, null, allStates),
            new RegisteredPacket("EX_PLEDGE_COUNT",0xFE, 0x13D, null, allStates),
            new RegisteredPacket("EX_ADENA_INVEN_COUNT",0xFE, 0x13E, null, allStates),
            new RegisteredPacket("EX_PLEDGE_RECRUIT_INFO",0xFE, 0x13F, null, allStates),
            new RegisteredPacket("EX_PLEDGE_RECRUIT_APPLY_INFO",0xFE, 0x140, null, allStates),
            new RegisteredPacket("EX_PLEDGE_RECRUIT_BOARD_SEARCH",0xFE, 0x141, null, allStates),
            new RegisteredPacket("EX_PLEDGE_RECRUIT_BOARD_DETAIL",0xFE, 0x142, null, allStates),
            new RegisteredPacket("EX_PLEDGE_WAITING_LIST_APPLIED",0xFE, 0x143, null, allStates),
            new RegisteredPacket("EX_PLEDGE_WAITING_LIST",0xFE, 0x144, null, allStates),
            new RegisteredPacket("EX_PLEDGE_WAITING_USER",0xFE, 0x145, null, allStates),
            new RegisteredPacket("EX_PLEDGE_DRAFT_LIST_SEARCH",0xFE, 0x146, null, allStates),
            new RegisteredPacket("EX_PLEDGE_WAITING_LIST_ALARM",0xFE, 0x147, null, allStates),
            new RegisteredPacket("EX_VALIDATE_ACTIVE_CHARACTER",0xFE, 0x148, null, allStates),
            new RegisteredPacket("EX_CLOSE_COMMISSION_REGISTER",0xFE, 0x149, null, allStates),
            new RegisteredPacket("EX_TELEPORT_TO_LOCATION_ACTIVATE",0xFE, 0x14A, null, allStates),
            new RegisteredPacket("EX_NOTIFY_WEB_PETITION_REPLY_ALARM",0xFE, 0x14B, null, allStates),
            new RegisteredPacket("EX_EVENT_SHOW_XMAS_WISH_CARD",0xFE, 0x14C, null, allStates),
            new RegisteredPacket("EX_INVITATION_EVENT_UI_SETTING",0xFE, 0x14D, null, allStates),
            new RegisteredPacket("EX_INVITATION_EVENT_INK_ENERGY",0xFE, 0x14E, null, allStates),
            new RegisteredPacket("EX_CHECK_ABUSING",0xFE, 0x14F, null, allStates),
            new RegisteredPacket("EX_GMVITALITY_EFFECT_INFO",0xFE, 0x150, null, allStates),
            new RegisteredPacket("EX_PATH_TO_AWAKENING_ALARM",0xFE, 0x151, null, allStates),
            new RegisteredPacket("EX_PUT_ENCHANT_SCROLL_ITEM_RESULT",0xFE, 0x152, null, allStates),
            new RegisteredPacket("EX_REMOVE_ENCHANT_SUPPORT_ITEM_RESULT",0xFE, 0x153, null, allStates),
            new RegisteredPacket("EX_SHOW_CARD_REWARD_LIST",0xFE, 0x154, null, allStates),
            new RegisteredPacket("EX_GM_VIEW_CHARACTER_INFO",0xFE, 0x155, null, allStates),
            new RegisteredPacket("EX_USER_INFO_EQUIP_SLOT",0xFE, 0x156, null, allStates),
            new RegisteredPacket("EX_USER_INFO_CUBIC",0xFE, 0x157, null, allStates),
            new RegisteredPacket("EX_USER_INFO_ABNORMAL_VISUAL_EFFECT",0xFE, 0x158, null, allStates),
            new RegisteredPacket("EX_USER_INFO_FISHING",0xFE, 0x159, null, allStates),
            new RegisteredPacket("EX_PARTY_SPELLED_INFO_UPDATE",0xFE, 0x15A, null, allStates),
            new RegisteredPacket("EX_DIVIDE_ADENA_START",0xFE, 0x15B, null, allStates),
            new RegisteredPacket("EX_DIVIDE_ADENA_CANCEL",0xFE, 0x15C, null, allStates),
            new RegisteredPacket("EX_DIVIDE_ADENA_DONE",0xFE, 0x15D, null, allStates),
            new RegisteredPacket("EX_PET_INFO",0xFE, 0x15E, null, allStates),
            new RegisteredPacket("EX_ACQUIRE_AP_SKILL_LIST",0xFE, 0x15F, null, allStates),
            new RegisteredPacket("EX_START_LUCKY_GAME",0xFE, 0x160, null, allStates),
            new RegisteredPacket("EX_BETTING_LUCKY_GAME_RESULT",0xFE, 0x161, null, allStates),
            new RegisteredPacket("EX_TRAINING_ZONE_ADMISSION",0xFE, 0x162, null, allStates),
            new RegisteredPacket("EX_TRAINING_ZONE_LEAVING",0xFE, 0x163, null, allStates),
            new RegisteredPacket("EX_PERIODIC_HENNA",0xFE, 0x164, null, allStates),
            new RegisteredPacket("EX_SHOW_AP_LIST_WND",0xFE, 0x165, null, allStates),
            new RegisteredPacket("EX_USER_INFO_INVEN_WEIGHT",0xFE, 0x166, null, allStates),
            new RegisteredPacket("EX_CLOSE_AP_LIST_WND",0xFE, 0x167, null, allStates),
            new RegisteredPacket("EX_ENCHANT_ONE_OK",0xFE, 0x168, null, allStates),
            new RegisteredPacket("EX_ENCHANT_ONE_FAIL",0xFE, 0x169, null, allStates),
            new RegisteredPacket("EX_ENCHANT_ONE_REMOVE_OK",0xFE, 0x16A, null, allStates),
            new RegisteredPacket("EX_ENCHANT_ONE_REMOVE_FAIL",0xFE, 0x16B, null, allStates),
            new RegisteredPacket("EX_ENCHANT_TWO_OK",0xFE, 0x16C, null, allStates),
            new RegisteredPacket("EX_ENCHANT_TWO_FAIL",0xFE, 0x16D, null, allStates),
            new RegisteredPacket("EX_ENCHANT_TWO_REMOVE_OK",0xFE, 0x16E, null, allStates),
            new RegisteredPacket("EX_ENCHANT_TWO_REMOVE_FAIL",0xFE, 0x16F, null, allStates),
            new RegisteredPacket("EX_ENCHANT_SUCESS",0xFE, 0x170, null, allStates),
            new RegisteredPacket("EX_ENCHANT_FAIL",0xFE, 0x171, null, allStates),
            new RegisteredPacket("EX_ENCHANT_RETRY_TO_PUT_ITEM_OK",0xFE, 0x172, null, allStates),
            new RegisteredPacket("EX_ENCHANT_RETRY_TO_PUT_ITEM_FAIL",0xFE, 0x173, null, allStates),
            new RegisteredPacket("EX_ACCOUNT_ATTENDANCE_INFO",0xFE, 0x174, null, allStates),
            new RegisteredPacket("EX_WORLD_CHAT_CNT",0xFE, 0x175, null, allStates),
            new RegisteredPacket("EX_ALCHEMY_SKILL_LIST",0xFE, 0x176, null, allStates),
            new RegisteredPacket("EX_TRY_MIX_CUBE",0xFE, 0x177, null, allStates),
            new RegisteredPacket("EX_ALCHEMY_CONVERSION",0xFE, 0x178, null, allStates),
            new RegisteredPacket("EX_BEAUTY_ITEM_LIST",0xFE, 0x179, null, allStates),
            new RegisteredPacket("EX_RECEIVE_CLIENT_INI",0xFE, 0x17A, null, allStates),
            new RegisteredPacket("EX_AUTO_FISH_AVAILABLE",0xFE, 0x17B, null, allStates),
            new RegisteredPacket("EX_CHANNEL_CHAT_ENTER_WORLD",0xFE, 0x17C, null, allStates),
            new RegisteredPacket("EX_CHANNEL_CHAT_PLEGE_INFO",0xFE, 0x17D, null, allStates),
            new RegisteredPacket("EX_VIP_ATTENDANCE_ITEM_LIST",0xFE, 0x17E, null, allStates),
            new RegisteredPacket("EX_CONFIRM_VIP_ATTENDANCE_CHECK",0xFE, 0x17F, null, allStates),
            new RegisteredPacket("EX_SHOW_ENSOUL_WINDOW",0xFE, 0x180, null, allStates),
            new RegisteredPacket("EX_ENSOUL_RESULT",0xFE, 0x181, null, allStates),
            new RegisteredPacket("EX_MULTISELL_RESULT",0xFE, 0x182, null, allStates),
            new RegisteredPacket("EX_CASTLE_WAR_SEASON_RESULT",0xFE, 0x183, null, allStates),
            new RegisteredPacket("EX_CASTLE_WAR_SEASON_REWARD",0xFE, 0x184, null, allStates),
            new RegisteredPacket("RECIVE_VIP_PRODUCT_LIST",0xFE, 0x185, null, allStates),
            new RegisteredPacket("RECIVE_VIP_LUCKY_GAME_INFO",0xFE, 0x186, null, allStates),
            new RegisteredPacket("RECIVE_VIP_LUCKY_GAME_ITEM_LIST",0xFE, 0x187, null, allStates),
            new RegisteredPacket("RECIVE_VIP_LUCKY_GAME_RESULT",0xFE, 0x188, null, allStates),
            new RegisteredPacket("RECIVE_VIP_INFO",0xFE, 0x189, null, allStates),
            new RegisteredPacket("RECIVE_VIP_INFO_REMAIN_TIME",0xFE, 0x18A, null, allStates),
            new RegisteredPacket("RECEIVE_VIP_BOT_CAPTCHA_IMAGE",0xFE, 0x18B, null, allStates),
            new RegisteredPacket("RECEIVE_VIP_BOT_CAPTCHA_ANSWER_RESULT",0xFE, 0x18C, null, allStates),
            new RegisteredPacket("EX_PLEDGE_SINGIN_FOR_OPEN_JOINING_METHOD",0xFE, 0x18D, null, allStates),
            new RegisteredPacket("EX_REQUEST_MATCH_ARENA",0xFE, 0x18E, null, allStates),
            new RegisteredPacket("EX_COMPLETE_MATCH_ARENA",0xFE, 0x18F, null, allStates),
            new RegisteredPacket("EX_CONFIRM_MATCH_ARENA",0xFE, 0x190, null, allStates),
            new RegisteredPacket("EX_CANCEL_MATCH_ARENA",0xFE, 0x191, null, allStates),
            new RegisteredPacket("EX_START_CHOOSE_CLASS_ARENA",0xFE, 0x192, null, allStates),
            new RegisteredPacket("EX_CHANGE_CLASS_ARENA",0xFE, 0x193, null, allStates),
            new RegisteredPacket("EX_CONFIRM_CLASS_ARENA",0xFE, 0x194, null, allStates),
            new RegisteredPacket("EX_START_BATTLE_READY_ARENA",0xFE, 0x195, null, allStates),
            new RegisteredPacket("EX_BATTLE_READY_ARENA",0xFE, 0x196, null, allStates),
            new RegisteredPacket("EX_DECO_NPC_INFO",0xFE, 0x197, null, allStates),
            new RegisteredPacket("EX_DECO_NPC_SET",0xFE, 0x198, null, allStates),
            new RegisteredPacket("EX_FACTION_INFO",0xFE, 0x199, null, allStates),
            new RegisteredPacket("EX_BATTLE_RESULT_ARENA",0xFE, 0x19A, null, allStates),
            new RegisteredPacket("EX_CLOSING_ARENA",0xFE, 0x19B, null, allStates),
            new RegisteredPacket("EX_CLOSED_ARENA",0xFE, 0x19C, null, allStates),
            new RegisteredPacket("EX_DIE_IN_ARENA",0xFE, 0x19D, null, allStates),
            new RegisteredPacket("DUMMY_PACKET",0xFE, 0x19E, null, allStates),
            new RegisteredPacket("EX_ARENA_DASHBOARD",0xFE, 0x19F, null, allStates),
            new RegisteredPacket("EX_ARENA_UPDATE_EQUIP_SLOT",0xFE, 0x1A0, null, allStates),
            new RegisteredPacket("EX_ARENA_KILL_INFO",0xFE, 0x1A1, null, allStates),
            new RegisteredPacket("EX_EXIT_ARENA",0xFE, 0x1A2, null, allStates),
            new RegisteredPacket("EX_BALTHUS_EVENT",0xFE, 0x1A3, null, allStates),
            new RegisteredPacket("EX_BALTHUS_EVENT_JACKPOT_USER",0xFE, 0x1A4, null, allStates),
            new RegisteredPacket("EX_PARTY_MATCHING_ROOM_HISTORY",0xFE, 0x1A5, null, allStates),
            new RegisteredPacket("EX_AI_CONTENT_UI_EVENT",0xFE, 0x1A6, null, allStates),
            new RegisteredPacket("EX_ARENA_CUSTOM_NOTIFICATION",0xFE, 0x1A7, null, allStates),
            new RegisteredPacket("EX_ONE_DAY_RECEIVE_REWARD_LIST",0xFE, 0x1A8, null, allStates),
            new RegisteredPacket("EX_CONNECTED_TIME_AND_GETTABLE_REWARD",0xFE, 0x1A9, null, allStates),
            new RegisteredPacket("EX_TODO_LIST_RECOMMAND",0xFE, 0x1AA, null, allStates),
            new RegisteredPacket("EX_TODO_LIST_INZONE",0xFE, 0x1AB, null, allStates),
            new RegisteredPacket("EX_TODO_LIST_HTML",0xFE, 0x1AC, null, allStates),
            new RegisteredPacket("EX_QUEUE_TICKET",0xFE, 0x1AD, null, allStates),
            new RegisteredPacket("EX_PLEDGE_BONUS_OPEN",0xFE, 0x1AE, null, allStates),
            new RegisteredPacket("EX_PLEDGE_BONUS_LIST",0xFE, 0x1AF, null, allStates),
            new RegisteredPacket("EX_PLEDGE_BONUS_MARK_RESET",0xFE, 0x1B0, null, allStates),
            new RegisteredPacket("EX_PLEDGE_BONUS_UPDATE",0xFE, 0x1B1, null, allStates),
            new RegisteredPacket("EX_SSO_AUTH_TOKEN",0xFE, 0x1B2, null, allStates),
            new RegisteredPacket("EX_QUEUE_TICKET_LOGIN",0xFE, 0x1B3, null, allStates),
            new RegisteredPacket("EX_ENSOUL_EXTRACTION_SHOW",0xFE, 0x1B4, null, allStates),
            new RegisteredPacket("EX_ENSOUL_EXTRACTION_RESULT",0xFE, 0x1B5, null, allStates),
            new RegisteredPacket("EX_FIELD_EVENT_STEP",0xFE, 0x1B6, null, allStates),
            new RegisteredPacket("EX_FIELD_EVENT_POINT",0xFE, 0x1B7, null, allStates),
            new RegisteredPacket("EX_FIELD_EVENT_EFFECT",0xFE, 0x1B8, null, allStates),
            new RegisteredPacket("EX_RAID_BOSS_SPAWN_INFO",0xFE, 0x1B9, null, allStates),
            new RegisteredPacket("EX_RAID_SERVER_INFO",0xFE, 0x1BA, null, allStates),
            new RegisteredPacket("EX_SHOW_AGIT_SIEGE_INFO",0xFE, 0x1BB, null, allStates),
            new RegisteredPacket("EX_ITEM_AUCTION_STATUS",0xFE, 0x1BC, null, allStates),
            new RegisteredPacket("EX_MONSTER_BOOK",0xFE, 0x1BD, null, allStates),
            new RegisteredPacket("EX_MONSTER_BOOK_REWARD_ICON",0xFE, 0x1BE, null, allStates),
            new RegisteredPacket("EX_MONSTER_BOOK_REWARD_FACTION_UI",0xFE, 0x1BF, null, allStates),
            new RegisteredPacket("EX_MONSTER_BOOK_OPEN_RESULT",0xFE, 0x1C0, null, allStates),
            new RegisteredPacket("EX_MONSTER_BOOK_CLOSE_FORCE",0xFE, 0x1C1, null, allStates),
            new RegisteredPacket("EX_FACTION_LEVEL_UP_NOTIFY",0xFE, 0x1C2, null, allStates),
            new RegisteredPacket("EX_ITEM_AUCTION_NEXT_INFO",0xFE, 0x1C3, null, allStates),
            new RegisteredPacket("EX_ITEM_AUCTION_UPDATE_BIDDING_INFO",0xFE, 0x1C4, null, allStates),
            new RegisteredPacket("EX_PRIVATE_STORE_BUYING_RESULT",0xFE, 0x1C5, null, allStates),
            new RegisteredPacket("EX_PRIVATE_STORE_SELLING_RESULT",0xFE, 0x1C6, null, allStates),
            new RegisteredPacket("EX_ENTER_WORLD",0xFE, 0x1C7, null, allStates),
            new RegisteredPacket("EX_MATCH_GROUP",0xFE, 0x1C8, null, allStates),
            new RegisteredPacket("EX_MATCH_GROUP_ASK",0xFE, 0x1C9, null, allStates),
            new RegisteredPacket("EX_MATCH_GROUP_WITHDRAW",0xFE, 0x1CA, null, allStates),
            new RegisteredPacket("EX_MATCH_GROUP_OUST",0xFE, 0x1CB, null, allStates),
            new RegisteredPacket("EX_ARENA_SHOW_ENEMY_PARTY_LOCATION",0xFE, 0x1CC, null, allStates),
            new RegisteredPacket("EX_SHOW_UPGRADE_SYSTEM",0xFE, 0x1CD, null, allStates),
            new RegisteredPacket("EX_UPGRADE_SYSTEM_RESULT",0xFE, 0x1CE, null, allStates),
            new RegisteredPacket("EX_CARD_UPDOWN_GAME_START",0xFE, 0x1CF, null, allStates),
            new RegisteredPacket("EX_CARD_UPDOWN_PICK_RESULT",0xFE, 0x1D0, null, allStates),
            new RegisteredPacket("EX_CARD_UPDOWN_GAME_PREPARE_REWARD",0xFE, 0x1D1, null, allStates),
            new RegisteredPacket("EX_CARD_UPDOWN_GAME_REWARD_REPLY",0xFE, 0x1D2, null, allStates),
            new RegisteredPacket("EX_CARD_UPDOWN_GAME_QUIT",0xFE, 0x1D3, null, allStates),
            new RegisteredPacket("EX_ARENA_RANK_ALL",0xFE, 0x1D4, null, allStates),
            new RegisteredPacket("EX_ARENA_MYRANK",0xFE, 0x1D5, null, allStates),
            new RegisteredPacket("EX_PLEDGE_CLASSIC_RAID_INFO",0xFE, 0x1D6, null, allStates),
            new RegisteredPacket("EX_ARENA_OBSERVE",0xFE, 0x1D7, null, allStates),
            new RegisteredPacket("EX_HTML_WITH_NPC_VIEWPORT",0xFE, 0x1D8, null, allStates),
            new RegisteredPacket("EX_PLEDGE_CONTRIBUTION_RANK",0xFE, 0x1D9, null, allStates),
            new RegisteredPacket("EX_PLEDGE_CONTRIBUTION_INFO",0xFE, 0x1DA, null, allStates),
            new RegisteredPacket("EX_PLEDGE_CONTRIBUTION_REWARD",0xFE, 0x1DB, null, allStates),
            new RegisteredPacket("EX_PLEDGE_RAID_INFO",0xFE, 0x1DC, null, allStates),
            new RegisteredPacket("EX_PLEDGE_RAID_RANK",0xFE, 0x1DD, null, allStates),
            new RegisteredPacket("EX_PLEDGE_LEVEL_UP",0xFE, 0x1DE, null, allStates),
            new RegisteredPacket("EX_PLEDGE_SHOW_INFO_UPDATE",0xFE, 0x1DF, null, allStates),
            new RegisteredPacket("EX_PLEDGE_MISSION_INFO",0xFE, 0x1E0, null, allStates),
            new RegisteredPacket("EX_PLEDGE_MISSION_REWARD_COUNT",0xFE, 0x1E1, null, allStates),
            new RegisteredPacket("EX_PLEDGE_MASTERY_INFO",0xFE, 0x1E2, null, allStates),
            new RegisteredPacket("EX_PLEDGE_MASTERY_SET",0xFE, 0x1E3, null, allStates),
            new RegisteredPacket("EX_PLEDGE_MASTERY_RESET",0xFE, 0x1E4, null, allStates),
            new RegisteredPacket("EX_TUTORIAL_SHOW_ID",0xFE, 0x1E5, null, allStates),
            new RegisteredPacket("EX_PLEDGE_SKILL_INFO",0xFE, 0x1E6, null, allStates),
            new RegisteredPacket("EX_PLEDGE_SKILL_ACTIVATE",0xFE, 0x1E7, null, allStates),
            new RegisteredPacket("EX_PLEDGE_ITEM_LIST",0xFE, 0x1E8, null, allStates),
            new RegisteredPacket("EX_PLEDGE_ITEM_ACTIVATE",0xFE, 0x1E9, null, allStates),
            new RegisteredPacket("EX_PLEDGE_ANNOUNCE",0xFE, 0x1EA, null, allStates),
            new RegisteredPacket("EX_PLEDGE_ANNOUNCE_SET",0xFE, 0x1EB, null, allStates),
            new RegisteredPacket("EX_SET_PLEDGE_EMBLEM",0xFE, 0x1EC, null, allStates),
            new RegisteredPacket("EX_SHOW_CREATE_PLEDGE",0xFE, 0x1ED, null, allStates),
            new RegisteredPacket("EX_PLEDGE_ITEM_INFO",0xFE, 0x1EE, null, allStates),
            new RegisteredPacket("EX_PLEDGE_ITEM_BUY",0xFE, 0x1EF, null, allStates),
            new RegisteredPacket("EX_ELEMENTAL_SPIRIT_INFO",0xFE, 0x1F0, null, allStates),
            new RegisteredPacket("EX_ELEMENTAL_SPIRIT_EXTRACT_INFO",0xFE, 0x1F1, null, allStates),
            new RegisteredPacket("EX_ELEMENTAL_SPIRIT_EVOLUTION_INFO",0xFE, 0x1F2, null, allStates),
            new RegisteredPacket("EX_ELEMENTAL_SPIRIT_EVOLUTION",0xFE, 0x1F3, null, allStates),
            new RegisteredPacket("EX_ELEMENTAL_SPIRIT_SET_TALENT",0xFE, 0x1F4, null, allStates),
            new RegisteredPacket("EX_ELEMENTAL_SPIRIT_ABSORB_INFO",0xFE, 0x1F5, null, allStates),
            new RegisteredPacket("EX_ELEMENTAL_SPIRIT_ABSORB",0xFE, 0x1F6, null, allStates),
            new RegisteredPacket("EX_CHOOSE_LOCKED_ITEM",0xFE, 0x1F7, null, allStates),
            new RegisteredPacket("EX_LOCKED_RESULT",0xFE, 0x1F8, null, allStates),
            // 152
            new RegisteredPacket("EX_ELEMENTAL_SPIRIT_EXTRACT",0xFE, 0x1F9, null, allStates),
            new RegisteredPacket("EX_OLYMPIAD_INFO",0xFE, 0x1FA, null, allStates),
            new RegisteredPacket("EX_OLYMPIAD_RECORD",0xFE, 0x1FB, null, allStates),
            new RegisteredPacket("EX_OLYMPIAD_MATCH_INFO",0xFE, 0x1FC, null, allStates),
            new RegisteredPacket("EX_ELEMENTAL_SPIRIT_GET_EXP",0xFE, 0x1FD, null, allStates),
            new RegisteredPacket("EX_ITEM_ANNOUNCE",0xFE, 0x1FE, null, allStates),
            new RegisteredPacket("EX_COMPLETED_DAILY_QUEST_LIST",0xFE, 0x1FF, null, allStates),
            new RegisteredPacket("EX_COMPLETED_DAILY_QUEST",0xFE, 0x200, null, allStates),
            new RegisteredPacket("EX_USER_BAN_INFO",0xFE, 0x201, null, allStates),
            new RegisteredPacket("EX_TRY_ENCHANT_ARTIFACT_RESULT",0xFE, 0x202, null, allStates),
            // 196
            new RegisteredPacket("EX_SHOW_UPGRADE_SYSTEM_NORMAL",0xFE, 0x203, null, allStates),
            new RegisteredPacket("EX_UPGRADE_SYSTEM_NORMAL_RESULT",0xFE, 0x204, null, allStates),
            new RegisteredPacket("EX_PURCHASE_LIMIT_SHOP_ITEM_LIST",0xFE, 0x205, null, allStates),
            new RegisteredPacket("EX_PURCHASE_LIMIT_SHOP_ITEM_BUY",0xFE, 0x206, null, allStates),
            new RegisteredPacket("EX_BLOODY_COIN_COUNT",0xFE, 0x207, null, allStates),
            new RegisteredPacket("EX_CLASS_CHANGE_SET_ALARM",0xFE, 0x208, null, allStates),
            new RegisteredPacket("EX_REQUEST_CLASS_CHANGE",0xFE, 0x209, null, allStates),
            new RegisteredPacket("EX_REQUEST_CLASS_CHANGE_VERIFYING",0xFE, 0x20A, null, allStates),
            new RegisteredPacket("EX_COSTUME_USE_ITEM",0xFE, 0x20B, null, allStates),
            new RegisteredPacket("EX_CHOOSE_COSTUME_ITEM",0xFE, 0x20C, null, allStates),
            new RegisteredPacket("EX_SEND_COSTUME_LIST",0xFE, 0x20D, null, allStates),
            new RegisteredPacket("EX_SEND_COSTUME_LIST_FULL",0xFE, 0x20E, null, allStates),
            new RegisteredPacket("EX_COSTUME_COLLECTION_SKILL_ACTIVE",0xFE, 0x20F, null, allStates),
            new RegisteredPacket("EX_COSTUME_EVOLUTION",0xFE, 0x210, null, allStates),
            new RegisteredPacket("EX_COSTUME_EXTRACT",0xFE, 0x211, null, allStates),
            new RegisteredPacket("EX_COSTUME_LOCK",0xFE, 0x212, null, allStates),
            new RegisteredPacket("EX_COSTUME_SHORTCUT_LIST",0xFE, 0x213, null, allStates),
            new RegisteredPacket("EX_MAGICLAMP_EXP_INFO",0xFE, 0x214, null, allStates),
            new RegisteredPacket("EX_MAGICLAMP_GAME_INFO",0xFE, 0x215, null, allStates),
            new RegisteredPacket("EX_MAGICLAMP_GAME_RESULT",0xFE, 0x216, null, allStates),
            // 228
            new RegisteredPacket("EX_SHOW_TELEPORT_UI",0xFE, 0x217, null, allStates),
            new RegisteredPacket("EX_ACTIVATE_AUTO_SHORTCUT",0xFE, 0x218, null, allStates),
            new RegisteredPacket("EX_PREMIUM_MANAGER_SHOW_HTML",0xFE, 0x219, null, allStates),
            new RegisteredPacket("EX_ACTIVATED_CURSED_TREASURE_BOX_LOCATION",0xFE, 0x21A, null, allStates),
            new RegisteredPacket("EX_PAYBACK_LIST",0xFE, 0x21B, null, allStates),
            new RegisteredPacket("EX_PAYBACK_GIVE_REWARD",0xFE, 0x21C, null, allStates),
            new RegisteredPacket("EX_PAYBACK_UI_LAUNCHER",0xFE, 0x21D, null, allStates),
            new RegisteredPacket("EX_DIE_INFO",0xFE, 0x21E, null, allStates),
            new RegisteredPacket("EX_AUTOPLAY_SETTING",0xFE, 0x21F, null, allStates),
            new RegisteredPacket("EX_AUTOPLAY_DO_MACRO",0xFE, 0x220, null, allStates),
            new RegisteredPacket("EX_OLYMPIAD_MATCH_MAKING_RESULT",0xFE, 0x221, null, allStates),
            new RegisteredPacket("EX_FESTIVAL_BM_INFO",0xFE, 0x222, null, allStates),
            new RegisteredPacket("EX_FESTIVAL_BM_ALL_ITEM_INFO",0xFE, 0x223, null, allStates),
            new RegisteredPacket("EX_FESTIVAL_BM_TOP_ITEM_INFO",0xFE, 0x224, null, allStates),
            new RegisteredPacket("EX_FESTIVAL_BM_GAME",0xFE, 0x225, null, allStates),
            new RegisteredPacket("EX_GACHA_SHOP_INFO",0xFE, 0x226, null, allStates),
            new RegisteredPacket("EX_GACHA_SHOP_GACHA_GROUP",0xFE, 0x227, null, allStates),
            new RegisteredPacket("EX_GACHA_SHOP_GACHA_ITEM",0xFE, 0x228, null, allStates),
            new RegisteredPacket("EX_TIME_RESTRICT_FIELD_LIST",0xFE, 0x229, null, allStates),
            new RegisteredPacket("EX_TIME_RESTRICT_FIELD_USER_ENTER",0xFE, 0x22A, null, allStates),
            new RegisteredPacket("EX_TIME_RESTRICT_FIELD_USER_CHARGE_RESULT",0xFE, 0x22B, null, allStates),
            new RegisteredPacket("EX_TIME_RESTRICT_FIELD_USER_ALARM",0xFE, 0x22C, null, allStates),
            new RegisteredPacket("EX_TIME_RESTRICT_FIELD_USER_EXIT",0xFE, 0x22D, null, allStates),
            new RegisteredPacket("EX_RANKING_CHAR_INFO",0xFE, 0x22E, null, allStates),
            new RegisteredPacket("EX_RANKING_CHAR_HISTORY",0xFE, 0x22F, null, allStates),
            new RegisteredPacket("EX_RANKING_CHAR_RANKERS",0xFE, 0x230, null, allStates),
            new RegisteredPacket("EX_RANKING_CHAR_BUFFZONE_NPC_INFO",0xFE, 0x231, null, allStates),
            new RegisteredPacket("EX_RANKING_CHAR_BUFFZONE_NPC_POSITION",0xFE, 0x232, null, allStates),
            new RegisteredPacket("EX_BOW_ACTION_TO",0xFE, 0x233, null, allStates),
            new RegisteredPacket("EX_MERCENARY_CASTLEWAR_CASTLE_INFO",0xFE, 0x234, null, allStates),
            new RegisteredPacket("EX_MERCENARY_CASTLEWAR_CASTLE_SIEGE_HUD_INFO",0xFE, 0x235, null, allStates),
            new RegisteredPacket("EX_MERCENARY_CASTLEWAR_CASTLE_SIEGE_INFO",0xFE, 0x236, null, allStates),
            new RegisteredPacket("EX_MERCENARY_CASTLEWAR_CASTLE_SIEGE_ATTACKER_LIST",0xFE, 0x237, null, allStates),
            new RegisteredPacket("EX_MERCENARY_CASTLEWAR_CASTLE_SIEGE_DEFENDER_LIST",0xFE, 0x238, null, allStates),
            new RegisteredPacket("EX_PLEDGE_MERCENARY_MEMBER_LIST",0xFE, 0x239, null, allStates),
            new RegisteredPacket("EX_PVPBOOK_LIST",0xFE, 0x23A, null, allStates),
            new RegisteredPacket("EX_PVPBOOK_KILLER_LOCATION",0xFE, 0x23B, null, allStates),
            new RegisteredPacket("EX_PVPBOOK_NEW_PK",0xFE, 0x23C, null, allStates),
            new RegisteredPacket("EX_PLEDGE_MERCENARY_MEMBER_JOIN",0xFE, 0x23D, null, allStates),
            new RegisteredPacket("EX_RAID_DROP_ITEM_ANNOUNCE",0xFE, 0x23E, null, allStates),
            new RegisteredPacket("EX_LETTER_COLLECTOR_UI_LAUNCHER",0xFE, 0x23F, null, allStates),
            new RegisteredPacket("EX_OLYMPIAD_MY_RANKING_INFO",0xFE, 0x240, null, allStates),
            new RegisteredPacket("EX_OLYMPIAD_RANKING_INFO",0xFE, 0x241, null, allStates),
            new RegisteredPacket("EX_OLYMPIAD_HERO_AND_LEGEND_INFO",0xFE, 0x242, null, allStates),
            new RegisteredPacket("EX_RAID_TELEPORT_INFO",0xFE, 0x243, null, allStates),
            new RegisteredPacket("EX_CRAFT_INFO",0xFE, 0x244, null, allStates),
            new RegisteredPacket("EX_CRAFT_EXTRACT",0xFE, 0x245, null, allStates),
            new RegisteredPacket("EX_CRAFT_RANDOM_INFO",0xFE, 0x246, null, allStates),
            new RegisteredPacket("EX_CRAFT_RANDOM_LOCK_SLOT",0xFE, 0x247, null, allStates),
            new RegisteredPacket("EX_CRAFT_RANDOM_REFRESH",0xFE, 0x248, null, allStates),
            new RegisteredPacket("EX_CRAFT_RANDOM_MAKE",0xFE, 0x249, null, allStates),
            new RegisteredPacket("EX_ITEM_ANNOUNCE_SETTING",0xFE, 0x24A, null, allStates),
            new RegisteredPacket("EX_USER_BOOST_STAT",0xFE, 0x24B, null, allStates),
            new RegisteredPacket("EX_ANTIBOT",0xFE, 0x24C, null, allStates),
            new RegisteredPacket("EX_DPSVR",0xFE, 0x24D, null, allStates),
            new RegisteredPacket("EX_SEND_CMD_LIST",0xFE, 0x24E, null, allStates),
            new RegisteredPacket("EX_SHANGHAI_HEALTHY_TIPS",0xFE, 0x24F, null, allStates),
            // 270
            new RegisteredPacket("EX_ADEN_FORTRESS_SIEGE_HUD_INFO",0xFE, 0x250, null, allStates),
            new RegisteredPacket("EX_PURCHASE_LIMIT_SHOP_ITEM_LIST_NEW",0xFE, 0x251, null, allStates),
            new RegisteredPacket("EX_SHARED_POSITION_SHARING_UI",0xFE, 0x252, null, allStates),
            new RegisteredPacket("EX_SHARED_POSITION_TELEPORT_UI",0xFE, 0x253, null, allStates),
            new RegisteredPacket("EX_CHAR_INFO",0xFE, 0x254, null, allStates),
            new RegisteredPacket("EX_AUTH_RECONNECT",0xFE, 0x255, null, allStates),
            new RegisteredPacket("EX_SHOW_HOMUNCULUS_BIRTH_INFO",0xFE, 0x256, null, allStates),
            new RegisteredPacket("EX_HOMUNCULUS_CREATE_START_RESULT",0xFE, 0x257, null, allStates),
            new RegisteredPacket("EX_HOMUNCULUS_INSERT_RESULT",0xFE, 0x258, null, allStates),
            new RegisteredPacket("EX_HOMUNCULUS_SUMMON_RESULT",0xFE, 0x259, null, allStates),
            new RegisteredPacket("EX_SHOW_HOMUNCULUS_LIST",0xFE, 0x25A, null, allStates),
            new RegisteredPacket("EX_DELETE_HOMUNCULUS_DATA_RESULT",0xFE, 0x25B, null, allStates),
            new RegisteredPacket("EX_ACTIVATE_HOMUNCULUS_RESULT",0xFE, 0x25C, null, allStates),
            new RegisteredPacket("EX_HOMUNCULUS_GET_ENCHANT_POINT_RESULT",0xFE, 0x25D, null, allStates),
            new RegisteredPacket("EX_HOMUNCULUS_INIT_POINT_RESULT",0xFE, 0x25E, null, allStates),
            new RegisteredPacket("EX_HOMUNCULUS_POINT_INFO",0xFE, 0x25F, null, allStates),
            new RegisteredPacket("EX_RESET_HOMUNCULUS_SKILL_RESULT",0xFE, 0x260, null, allStates),
            new RegisteredPacket("EX_ENCHANT_HOMUNCULUS_SKILL_RESULT",0xFE, 0x261, null, allStates),
            new RegisteredPacket("EX_HOMUNCULUS_ENCHANT_EXP_RESULT",0xFE, 0x262, null, allStates),
            new RegisteredPacket("EX_HOMUNCULUS_HPSPVP",0xFE, 0x263, null, allStates),
            new RegisteredPacket("EX_HOMUNCULUS_READY",0xFE, 0x264, null, allStates),
            new RegisteredPacket("EX_TELEPORT_FAVORITES_LIST",0xFE, 0x265, null, allStates),
            new RegisteredPacket("EX_VITAL_EX_INFO",0xFE, 0x266, null, allStates),
            new RegisteredPacket("EX_NET_LATENCY",0xFE, 0x267, null, allStates),
            new RegisteredPacket("EX_MABLE_GAME_SHOW_PLAYER_STATE",0xFE, 0x268, null, allStates),
            new RegisteredPacket("EX_MABLE_GAME_DICE_RESULT",0xFE, 0x269, null, allStates),
            new RegisteredPacket("EX_MABLE_GAME_MOVE",0xFE, 0x26A, null, allStates),
            new RegisteredPacket("EX_MABLE_GAME_PRISON",0xFE, 0x26B, null, allStates),
            new RegisteredPacket("EX_MABLE_GAME_REWARD_ITEM",0xFE, 0x26C, null, allStates),
            new RegisteredPacket("EX_MABLE_GAME_SKILL_INFO",0xFE, 0x26D, null, allStates),
            new RegisteredPacket("EX_MABLE_GAME_MINIGAME",0xFE, 0x26E, null, allStates),
            new RegisteredPacket("EX_MABLE_GAME_PLAY_UNABLE",0xFE, 0x26F, null, allStates),
            new RegisteredPacket("EX_MABLE_GAME_UI_LAUNCHER",0xFE, 0x270, null, allStates),
            new RegisteredPacket("EX_MABLE_GAME_ROLL_COUNT_RESET",0xFE, 0x271, null, allStates),
            new RegisteredPacket("EX_PET_SKILL_LIST",0xFE, 0x272, null, allStates),
            new RegisteredPacket("EX_OPEN_BLESS_OPTION_SCROLL",0xFE, 0x273, null, allStates),
            new RegisteredPacket("EX_BLESS_OPTION_PUT_ITEM",0xFE, 0x274, null, allStates),
            new RegisteredPacket("EX_BLESS_OPTION_ENCHANT",0xFE, 0x275, null, allStates),
            new RegisteredPacket("EX_BLESS_OPTION_CANCEL",0xFE, 0x276, null, allStates),
            new RegisteredPacket("EX_PVP_RANKING_MY_INFO",0xFE, 0x277, null, allStates),
            new RegisteredPacket("EX_PVP_RANKING_LIST",0xFE, 0x278, null, allStates),
            new RegisteredPacket("EX_PLEDGE_V3_INFO",0xFE, 0x279, null, allStates),
            new RegisteredPacket("EX_PLEDGE_ENEMY_INFO_LIST",0xFE, 0x27A, null, allStates),
            new RegisteredPacket("EX_ITEM_DELETION_INFO",0xFE, 0x27B, null, allStates),
            // 272
            new RegisteredPacket("EX_PK_PENALTY_LIST",0xFE, 0x27C, null, allStates),
            new RegisteredPacket("EX_PK_PENALTY_LIST_ONLY_LOC",0xFE, 0x27D, null, allStates),
            new RegisteredPacket("EX_SHOW_PET_EXTRACT_SYSTEM",0xFE, 0x27E, null, allStates),
            new RegisteredPacket("EX_RESULT_PET_EXTRACT_SYSTEM",0xFE, 0x27F, null, allStates),
            new RegisteredPacket("EX_HIDE_PET_EXTRACT_SYSTEM",0xFE, 0x280, null, allStates),
            // 306
            new RegisteredPacket("EX_RANKING_FESTIVAL_SIDEBAR_INFO",0xFE, 0x281, null, allStates),
            new RegisteredPacket("EX_RANKING_FESTIVAL_BUY",0xFE, 0x282, null, allStates),
            new RegisteredPacket("EX_RANKING_FESTIVAL_BONUS",0xFE, 0x283, null, allStates),
            new RegisteredPacket("EX_RANKING_FESTIVAL_RANKING",0xFE, 0x284, null, allStates),
            new RegisteredPacket("EX_RANKING_FESTIVAL_MYINFO",0xFE, 0x285, null, allStates),
            new RegisteredPacket("EX_RANKING_FESTIVAL_MY_RECEIVED_BONUS",0xFE, 0x286, null, allStates),
            new RegisteredPacket("EX_RANKING_FESTIVAL_REWARD",0xFE, 0x287, null, allStates),
            new RegisteredPacket("EX_TIMER_CHECK",0xFE, 0x288, null, allStates),
            new RegisteredPacket("EX_STEADY_BOX_UI_INIT",0xFE, 0x289, null, allStates),
            new RegisteredPacket("EX_STEADY_ALL_BOX_UPDATE",0xFE, 0x28A, null, allStates),
            new RegisteredPacket("EX_STEADY_ONE_BOX_UPDATE",0xFE, 0x28B, null, allStates),
            new RegisteredPacket("EX_STEADY_BOX_REWARD",0xFE, 0x28C, null, allStates),
            new RegisteredPacket("EX_PET_RANKING_MY_INFO",0xFE, 0x28D, null, allStates),
            new RegisteredPacket("EX_PET_RANKING_LIST",0xFE, 0x28E, null, allStates),
            new RegisteredPacket("EX_COLLECTION_INFO",0xFE, 0x28F, null, allStates),
            new RegisteredPacket("EX_COLLECTION_OPEN_UI",0xFE, 0x290, null, allStates),
            new RegisteredPacket("EX_COLLECTION_CLOSE_UI",0xFE, 0x291, null, allStates),
            new RegisteredPacket("EX_COLLECTION_LIST",0xFE, 0x292, null, allStates),
            new RegisteredPacket("EX_COLLECTION_UPDATE_FAVORITE",0xFE, 0x293, null, allStates),
            new RegisteredPacket("EX_COLLECTION_FAVORITE_LIST",0xFE, 0x294, null, allStates),
            new RegisteredPacket("EX_COLLECTION_SUMMARY",0xFE, 0x295, null, allStates),
            new RegisteredPacket("EX_COLLECTION_REGISTER",0xFE, 0x296, null, allStates),
            new RegisteredPacket("EX_COLLECTION_COMPLETE",0xFE, 0x297, null, allStates),
            new RegisteredPacket("EX_COLLECTION_RECEIVE_REWARD",0xFE, 0x298, null, allStates),
            new RegisteredPacket("EX_COLLECTION_RESET",0xFE, 0x299, null, allStates),
            new RegisteredPacket("EX_COLLECTION_ACTIVE_EVENT",0xFE, 0x29A, null, allStates),
            new RegisteredPacket("EX_COLLECTION_RESET_REWARD",0xFE, 0x29B, null, allStates),
            new RegisteredPacket("EX_PVPBOOK_SHARE_REVENGE_LIST",0xFE, 0x29C, null, allStates),
            new RegisteredPacket("EX_PVPBOOK_SHARE_REVENGE_KILLER_LOCATION",0xFE, 0x29D, null, allStates),
            new RegisteredPacket("EX_PVPBOOK_SHARE_REVENGE_NEW_REVENGEINFO",0xFE, 0x29E, null, allStates),
            new RegisteredPacket("EX_PENALTY_ITEM_DROP",0xFE, 0x29F, null, allStates),
            new RegisteredPacket("EX_PENALTY_ITEM_LIST",0xFE, 0x2A0, null, allStates),
            new RegisteredPacket("EX_PENALTY_ITEM_RESTORE",0xFE, 0x2A1, null, allStates),
            new RegisteredPacket("EX_USER_WATCHER_TARGET_LIST",0xFE, 0x2A2, null, allStates),
            new RegisteredPacket("EX_USER_WATCHER_TARGET_STATUS",0xFE, 0x2A3, null, allStates),
            new RegisteredPacket("EX_HOMUNCULUS_ACTIVATE_SLOT_RESULT",0xFE, 0x2A4, null, allStates),
            new RegisteredPacket("EX_SHOW_HOMUNCULUS_COUPON_UI",0xFE, 0x2A5, null, allStates),
            new RegisteredPacket("EX_SUMMON_HOMUNCULUS_COUPON_RESULT",0xFE, 0x2A6, null, allStates),
            new RegisteredPacket("EX_PENALTY_ITEM_INFO",0xFE, 0x2A7, null, allStates),
            new RegisteredPacket("EX_MAGIC_SKILL_USE_GROUND",0xFE, 0x2A8, null, allStates),
            new RegisteredPacket("EX_SUBJUGATION_SIDEBAR",0xFE, 0x2A9, null, allStates),
            new RegisteredPacket("EX_SUBJUGATION_LIST",0xFE, 0x2AA, null, allStates),
            new RegisteredPacket("EX_SUBJUGATION_RANKING",0xFE, 0x2AB, null, allStates),
            new RegisteredPacket("EX_SUBJUGATION_GACHA_UI",0xFE, 0x2AC, null, allStates),
            new RegisteredPacket("EX_SUBJUGATION_GACHA",0xFE, 0x2AD, null, allStates),
            new RegisteredPacket("EX_USER_VIEW_INFO_PARAMETER",0xFE, 0x2AE, null, allStates),
            new RegisteredPacket("EX_PLEDGE_DONATION_INFO",0xFE, 0x2AF, null, allStates),
            new RegisteredPacket("EX_PLEDGE_DONATION_REQUEST",0xFE, 0x2B0, null, allStates),
            new RegisteredPacket("EX_PLEDGE_CONTRIBUTION_LIST",0xFE, 0x2B1, null, allStates),
            new RegisteredPacket("EX_PLEDGE_RANKING_MY_INFO",0xFE, 0x2B2, null, allStates),
            new RegisteredPacket("EX_PLEDGE_RANKING_LIST",0xFE, 0x2B3, null, allStates),
            new RegisteredPacket("EX_ITEM_RESTORE_LIST",0xFE, 0x2B4, null, allStates),
            new RegisteredPacket("EX_ITEM_RESTORE",0xFE, 0x2B5, null, allStates),
            new RegisteredPacket("EX_PLEDGE_COIN_INFO",0xFE, 0x2B6, null, allStates),
            // 338
            new RegisteredPacket("EX_DETHRONE_INFO",0xFE, 0x2B7, null, allStates),
            new RegisteredPacket("EX_DETHRONE_RANKING_INFO",0xFE, 0x2B8, null, allStates),
            new RegisteredPacket("EX_DETHRONE_SERVER_INFO",0xFE, 0x2B9, null, allStates),
            new RegisteredPacket("EX_DETHRONE_DISTRICT_OCCUPATION_INFO",0xFE, 0x2BA, null, allStates),
            new RegisteredPacket("EX_DETHRONE_DAILY_MISSION_INFO",0xFE, 0x2BB, null, allStates),
            new RegisteredPacket("EX_DETHRONE_DAILY_MISSION_GET_REWARD",0xFE, 0x2BC, null, allStates),
            new RegisteredPacket("EX_DETHRONE_DAILY_MISSION_COMPLETE",0xFE, 0x2BD, null, allStates),
            new RegisteredPacket("EX_DETHRONE_PREV_SEASON_INFO",0xFE, 0x2BE, null, allStates),
            new RegisteredPacket("EX_DETHRONE_GET_REWARD",0xFE, 0x2BF, null, allStates),
            new RegisteredPacket("EX_DETHRONE_CHECK_NAME",0xFE, 0x2C0, null, allStates),
            new RegisteredPacket("EX_DETHRONE_CHANGE_NAME",0xFE, 0x2C1, null, allStates),
            new RegisteredPacket("EX_DETHRONE_CONNECT_CASTLE",0xFE, 0x2C2, null, allStates),
            new RegisteredPacket("EX_DETHRONE_DISCONNECT_CASTLE",0xFE, 0x2C3, null, allStates),
            new RegisteredPacket("EX_DETHRONE_SEASON_INFO",0xFE, 0x2C4, null, allStates),
            new RegisteredPacket("EX_SERVERLIMIT_ITEM_ANNOUNCE",0xFE, 0x2C5, null, allStates),
            new RegisteredPacket("EX_CHANGE_NICKNAME_COLOR_ICON",0xFE, 0x2C6, null, allStates),
            new RegisteredPacket("EX_WORLDCASTLEWAR_HOST_CASTLE_SIEGE_HUD_INFO",0xFE, 0x2C7, null, allStates),
            new RegisteredPacket("EX_WORLDCASTLEWAR_CASTLE_INFO",0xFE, 0x2C8, null, allStates),
            new RegisteredPacket("EX_WORLDCASTLEWAR_CASTLE_SIEGE_INFO",0xFE, 0x2C9, null, allStates),
            new RegisteredPacket("EX_WORLDCASTLEWAR_CASTLE_SIEGE_HUD_INFO",0xFE, 0x2CA, null, allStates),
            new RegisteredPacket("EX_WORLDCASTLEWAR_CASTLE_SIEGE_ATTACKER_LIST",0xFE, 0x2CB, null, allStates),
            new RegisteredPacket("EX_WORLDCASTLEWAR_PLEDGE_MERCENARY_MEMBER_LIST",0xFE, 0x2CC, null, allStates),
            new RegisteredPacket("EX_WORLDCASTLEWAR_PLEDGE_MERCENARY_MEMBER_JOIN",0xFE, 0x2CD, null, allStates),
            new RegisteredPacket("EX_WORLDCASTLEWAR_SIEGE_MAINBATTLE_OCCUPY_INFO",0xFE, 0x2CE, null, allStates),
            new RegisteredPacket("EX_WORLDCASTLEWAR_SIEGE_MAINBATTLE_HERO_WEAPON_INFO",0xFE, 0x2CF, null, allStates),
            new RegisteredPacket("EX_WORLDCASTLEWAR_SIEGE_MAINBATTLE_HERO_WEAPON_USER",0xFE, 0x2D0, null, allStates),
            new RegisteredPacket("EX_WORLDCASTLEWAR_SIEGE_MAINBATTLE_SIEGE_GOLEM_INFO",0xFE, 0x2D1, null, allStates),
            new RegisteredPacket("EX_WORLDCASTLEWAR_SIEGE_MAINBATTLE_DOOR_INFO",0xFE, 0x2D2, null, allStates),
            new RegisteredPacket("EX_WORLDCASTLEWAR_SIEGE_MAINBATTLE_HUD_INFO",0xFE, 0x2D3, null, allStates),
            new RegisteredPacket("EX_PRIVATE_STORE_SEARCH_ITEM",0xFE, 0x2D4, null, allStates),
            new RegisteredPacket("EX_PRIVATE_STORE_SEARCH_HISTORY",0xFE, 0x2D5, null, allStates),
            new RegisteredPacket("EX_PRIVATE_STORE_SEARCH_STATISTICS",0xFE, 0x2D6, null, allStates),
            new RegisteredPacket("EX_NEW_HENNA_LIST",0xFE, 0x2D7, null, allStates),
            new RegisteredPacket("EX_NEW_HENNA_EQUIP",0xFE, 0x2D8, null, allStates),
            new RegisteredPacket("EX_NEW_HENNA_UNEQUIP",0xFE, 0x2D9, null, allStates),
            new RegisteredPacket("EX_NEW_HENNA_POTEN_SELECT",0xFE, 0x2DA, null, allStates),
            new RegisteredPacket("EX_NEW_HENNA_POTEN_ENCHANT",0xFE, 0x2DB, null, allStates),
            new RegisteredPacket("EX_NEW_HENNA_COMPOSE",0xFE, 0x2DC, null, allStates),
            new RegisteredPacket("EX_REQUEST_INVITE_PARTY",0xFE, 0x2DD, null, allStates),
            new RegisteredPacket("EX_INIT_GLOBAL_EVENT_UI",0xFE, 0x2DE, null, allStates),
            new RegisteredPacket("EX_SHOW_GLOBAL_EVENT_UI",0xFE, 0x2DF, null, allStates),
            new RegisteredPacket("EX_L2PASS_SIMPLE_INFO",0xFE, 0x2E0, null, allStates),
            new RegisteredPacket("EX_L2PASS_INFO",0xFE, 0x2E1, null, allStates),
            new RegisteredPacket("EX_SAYHAS_SUPPORT_INFO",0xFE, 0x2E2, null, allStates),
            // 362
            new RegisteredPacket("EX_RES_ENCHANT_ITEM_FAIL_REWARD_INFO",0xFE, 0x2E3, null, allStates),
            new RegisteredPacket("EX_CHANGED_ENCHANT_TARGET_ITEM_PROB_LIST",0xFE, 0x2E4, null, allStates),
            new RegisteredPacket("EX_ENCHANT_CHALLENGE_POINT_INFO",0xFE, 0x2E5, null, allStates),
            new RegisteredPacket("EX_SET_ENCHANT_CHALLENGE_POINT",0xFE, 0x2E6, null, allStates),
            new RegisteredPacket("EX_RESET_ENCHANT_CHALLENGE_POINT",0xFE, 0x2E7, null, allStates),
            new RegisteredPacket("EX_RES_SELECT_MULTI_ENCHANT_SCROLL",0xFE, 0x2E8, null, allStates),
            new RegisteredPacket("EX_RES_SET_MULTI_ENCHANT_ITEM_LIST",0xFE, 0x2E9, null, allStates),
            new RegisteredPacket("EX_RES_MULTI_ENCHANT_ITEM_LIST",0xFE, 0x2EA, null, allStates),
            new RegisteredPacket("EX_WORLDCASTLEWAR_HOST_SUPPORT_PLEDGE_RANKING_INFO",0xFE, 0x2EB, null, allStates),
            new RegisteredPacket("EX_WORLDCASTLEWAR_HOST_PLEDGE_RANKING_INFO",0xFE, 0x2EC, null, allStates),
            new RegisteredPacket("EX_WORLDCASTLEWAR_HOST_PERSONAL_RANKING_INFO",0xFE, 0x2ED, null, allStates),
            new RegisteredPacket("EX_WORLDCASTLEWAR_SUPPORT_PLEDGE_RANKING_INFO",0xFE, 0x2EE, null, allStates),
            new RegisteredPacket("EX_WORLDCASTLEWAR_PLEDGE_RANKING_INFO",0xFE, 0x2EF, null, allStates),
            new RegisteredPacket("EX_WORLDCASTLEWAR_PERSONAL_RANKING_INFO",0xFE, 0x2F0, null, allStates),
            new RegisteredPacket("EX_HOMUNCULUS_CREATE_PROB_LIST",0xFE, 0x2F1, null, allStates),
            new RegisteredPacket("EX_HOMUNCULUS_COUPON_PROB_LIST",0xFE, 0x2F2, null, allStates),
            new RegisteredPacket("EX_WORLDCASTLEWAR_HOST_CASTLE_SIEGE_RANKING_INFO",0xFE, 0x2F3, null, allStates),
            new RegisteredPacket("EX_WORLDCASTLEWAR_CASTLE_SIEGE_RANKING_INFO",0xFE, 0x2F4, null, allStates),
            new RegisteredPacket("EX_MISSION_LEVEL_REWARD_LIST",0xFE, 0x2F5, null, allStates),
            new RegisteredPacket("EX_BALROGWAR_SHOW_UI",0xFE, 0x2F6, null, allStates),
            new RegisteredPacket("EX_BALROGWAR_SHOW_RANKING",0xFE, 0x2F7, null, allStates),
            new RegisteredPacket("EX_BALROGWAR_GET_REWARD",0xFE, 0x2F8, null, allStates),
            new RegisteredPacket("EX_BALROGWAR_HUD",0xFE, 0x2F9, null, allStates),
            new RegisteredPacket("EX_BALROGWAR_BOSSINFO",0xFE, 0x2FA, null, allStates),
            new RegisteredPacket("EX_USER_RESTART_LOCKER_LIST",0xFE, 0x2FB, null, allStates),
            new RegisteredPacket("EX_USER_RESTART_LOCKER_UPDATE",0xFE, 0x2FC, null, allStates),
            new RegisteredPacket("EX_WORLD_EXCHANGE_ITEM_LIST",0xFE, 0x2FD, null, allStates),
            new RegisteredPacket("EX_WORLD_EXCHANGE_REGI_ITEM",0xFE, 0x2FE, null, allStates),
            new RegisteredPacket("EX_WORLD_EXCHANGE_BUY_ITEM",0xFE, 0x2FF, null, allStates),
            new RegisteredPacket("EX_WORLD_EXCHANGE_SETTLE_LIST",0xFE, 0x300, null, allStates),
            new RegisteredPacket("EX_WORLD_EXCHANGE_SETTLE_RECV_RESULT",0xFE, 0x301, null, allStates),
            new RegisteredPacket("EX_WORLD_EXCHANGE_SELL_COMPLETE_ALARM",0xFE, 0x302, null, allStates),
            new RegisteredPacket("EX_READY_ITEM_AUTO_PEEL",0xFE, 0x303, null, allStates),
            new RegisteredPacket("EX_RESULT_ITEM_AUTO_PEEL",0xFE, 0x304, null, allStates),
            new RegisteredPacket("EX_STOP_ITEM_AUTO_PEEL",0xFE, 0x305, null, allStates),
            new RegisteredPacket("EX_TIME_RESTRICT_FIELD_DIE_LIMT_TIME",0xFE, 0x306, null, allStates),
            new RegisteredPacket("EX_APPLY_VARIATION_OPTION",0xFE, 0x307, null, allStates),
            new RegisteredPacket("EX_BR_VERSION",0xFE, 0x308, null, allStates),
            new RegisteredPacket("EX_MAX",0xFE, 0x309, null, allStates),
        };
    }
}
